import type { Metadata } from "next";
import { Compass, Crosshair, Database, Filter } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Keyword Opportunity Research — SEOForge", description: "Prioritize search opportunities using intent, business fit, SERP evidence, current coverage and realistic authority.", alternates: { canonical: "/platform/content-growth/keyword-research" } };

export default function KeywordResearchPage() {
  return <PublicShell>
    <PublicHero eyebrow="Keyword opportunity research" title="Stop choosing content from volume alone." description="SEOForge turns a market, product and audience into a defensible opportunity backlog. Each candidate carries intent, business fit, SERP composition, current site coverage, difficulty evidence and a recommended next artifact." primary="Choose a Content Plan" primaryHref="/pricing" secondary="See the Content Pipeline" secondaryHref="/platform/content-growth" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Opportunity shortlist</p><div className="mt-4 space-y-3">{[["oauth vs api key","92","comparison"],["rotate api credentials","86","how-to"],["api key security","61","guide"]].map(([q,s,i])=><div key={q} className="grid grid-cols-[1fr_auto] gap-4 rounded-xl border border-edge p-4"><div><p className="text-sm font-semibold">{q}</p><p className="mt-1 text-[10px] text-fg-faint">intent · {i}</p></div><span className="display text-lg text-primary">{s}</span></div>)}</div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Customer problem" title="A spreadsheet of keywords is not an editorial decision." body="Volume-heavy lists ignore whether a query serves the buyer, duplicates an existing page or sits inside a SERP the site can credibly compete in."/><PublicChecklist negative items={["No mapping to the product or customer journey","No check against published and scheduled pages","No evidence explaining why this opportunity comes first"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Input → finished output</p><p className="mt-5 text-sm"><b>Input:</b> developer security product, US market, engineering managers, repository docs + blog.</p><p className="mt-4 text-sm"><b>Output:</b> a ranked opportunity packet led by “OAuth vs API key,” recommended as a comparison article with an implementation decision tree.</p><PublicChecklist items={["Observed SERP types and competing page formats","Coverage overlap with /docs/authentication","Primary intent, secondary questions and excluded angles","Business relevance, confidence and proposed article role"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Research workflow" title="Evidence narrows the backlog before writing begins."/><div className="mt-10"><PublicSteps steps={["Define audience, market, product motions and exclusions","Expand seed topics using customer language and provider observations","Inspect intent, SERP features and representative ranking pages","Compare candidates with the existing site and active calendar","Score business fit, evidence confidence, effort and differentiation","Route the approved opportunity into a content brief"]} accent="mint"/></div></PublicSection>
    <PublicSection><PublicHeading eyebrow="Decision surface" title="Review why the opportunity deserves capacity."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Compass} title="Intent" body="The job the searcher expects to complete, with mixed intent called out."/><PublicCard icon={Crosshair} tone="amber" title="Fit" body="Connection to a real audience, product capability and conversion path."/><PublicCard icon={Database} tone="mint" title="Evidence" body="Timestamped provider observations, visible SERP features and site coverage."/><PublicCard icon={Filter} tone="rose" title="Exclusions" body="Duplicates, weak-fit traffic and unsupported claims removed from the queue."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><div className="marketing-card p-6"><p className="text-sm font-semibold">Human review</p><p className="mt-3 text-sm leading-6 text-fg-mute">Approve the opportunity, change its content type, defer it or reject it. Approval reserves capacity for briefing; it does not publish content.</p></div><div className="marketing-card p-6"><p className="text-sm font-semibold">Capacity and measurement</p><p className="mt-3 text-sm leading-6 text-fg-mute">Plans bound provider lookups, active markets and production capacity. After publishing, the opportunity is measured by query coverage, qualified engagement and conversions—not volume forecasts alone.</p></div></div></PublicSection>
    <PublicFaq items={[["Is search volume the priority score?","No. Intent, business fit, current authority, SERP composition, differentiation, effort and confidence also matter."],["Can I bring my own keyword list?","Yes. Imported candidates go through the same evidence and duplication review."],["Does SEOForge copy competitor topics?","No. Competitor coverage is one observation; the proposed page must serve your audience with an original purpose."],["What does a human approve?","The prioritized opportunity, intended page type, audience, scope and capacity reservation."],["Are traffic estimates guaranteed?","No. Forecasts are planning inputs, not promises of impressions, clicks or revenue."]]}/>
    <PublicCta title="Turn market evidence into an approved content backlog." body="Choose a paid plan to connect your site, markets and provider capacity to the Content Growth pipeline."/>
  </PublicShell>;
}
