import type { Metadata } from "next";
import { Braces, Gauge, Link2Off, Route } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Continuous Technical SEO — SEOForge", description: "Detect technical regressions, prepare exact fixes and validate crawl, schema, links and performance after deployment.", alternates: { canonical: "/platform/search-optimization/technical-seo" } };

export default function TechnicalSeoPage() {
  return <PublicShell>
    <PublicHero eyebrow="Technical SEO" title="Catch the production regression while the fix is still small." description="SEOForge monitors crawlability, index directives, canonicals, redirects, sitemaps, structured data, internal links and performance—then prepares a framework-native or CMS-native correction for approval." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="See Production Validation" secondaryHref="/platform/production-validation" visual={<div className="marketing-card p-5 font-mono text-[11px]"><p className="text-fg-faint">CRAWL DIFF · deploy a91f3</p><p className="mt-4 text-rose">12 new canonical mismatches</p><p className="mt-2 text-rose">7 sitemap URLs return 308</p><p className="mt-2 text-amber">FAQ schema missing required name</p><p className="mt-4 rounded border border-mint/25 bg-mint/8 p-3 text-mint">proposed: canonical helper + sitemap source fix</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Evidence collected" title="The finding includes scope, cause and affected templates."/><PublicChecklist items={["Crawl samples before and after deployment a91f3","Rendered canonical, robots and status for 12 affected guide URLs","Sitemap source traced to the deprecated slug helper","JSON-LD validation with exact missing property","Repository history identifying the shared template change"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Exact proposed change</p><p className="mt-5 font-mono text-xs text-rose">- canonical: baseUrl + legacySlug</p><p className="mt-2 font-mono text-xs text-mint">+ canonical: new URL(request.url).pathname</p><p className="mt-5 text-sm leading-6 text-fg-mute">Also update the sitemap to emit final destinations, add the required FAQ name and cover both helpers with regression tests.</p></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Technical workflow" title="Detect, isolate, fix and prove the live result."/><div className="mt-10"><PublicSteps steps={["Compare scheduled crawl and deployment-triggered checks","Group affected URLs by template, status and shared cause","Prioritize indexability impact, confidence, scope and risk","Prepare the smallest code, configuration or CMS change","Run type, build, crawl, schema, link and preview checks","Require human approval; deploy and repeat live validation"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Route} title="Index path" body="Robots, canonical, status, redirects and sitemap agree on the preferred URL."/><PublicCard icon={Braces} tone="mint" title="Structured data" body="Rendered JSON-LD is checked against the actual visible page and required properties."/><PublicCard icon={Link2Off} tone="rose" title="Link integrity" body="Broken, redirected and orphaned paths become scoped changes rather than a raw export."/><PublicCard icon={Gauge} tone="amber" title="Performance" body="Lab comparisons are kept separate from available field evidence and device context."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human approval and rollback" body="Review the file diff, affected URL sample, build evidence, screenshots, risk and revert commit before production."/><PublicCard title="Capacity and measurement" body="Crawl depth, check cadence and execution use paid plan capacity. Success means the verified technical state changed—not a promised ranking gain."/></div></PublicSection>
    <PublicFaq items={[["Is this a downloadable audit?","No. Continuous monitoring connects each qualified finding to an exact proposal and post-deploy check."],["Can SEOForge change robots.txt automatically?","It can prepare and validate a proposal, but a human must approve production."],["How are false positives reduced?","Findings are grouped by template, reproduced in rendered output and checked against repository or CMS state."],["What happens if validation fails?","The proposal stays blocked or a rollback proposal is prepared; failure cannot be self-approved."],["Will fixing an error improve rankings?","It can remove a technical obstacle, but rankings remain controlled by search engines."]]}/>
    <PublicCta title="Move technical SEO from report backlog to validated production work." body="Choose a paid plan with the crawl, monitoring and implementation capacity your site requires."/>
  </PublicShell>;
}
