import type { Metadata } from "next";
import { Network, ShoppingBag, Tags } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"SEO Automation for Ecommerce — SEOForge",description:"Coordinate category, product and editorial growth with technical quality and revenue measurement.",alternates:{canonical:"/seo-automation-for-ecommerce"}};
export default function SeoAutomationForEcommercePage(){return <PublicShell>
 <PublicHero eyebrow="SEO automation for ecommerce" title="Grow organic discovery without multiplying thin categories and duplicate pages." description="SEOForge coordinates category, product-supporting and editorial work while monitoring faceting, indexability, schema, internal links and organic conversion evidence." primary="Choose Your Plan" primaryHref="/pricing" secondary="Book an Ecommerce Demo" secondaryHref="/demo" visual={<div className="marketing-card p-7"><ShoppingBag className="text-primary"/><p className="mt-5 font-semibold">Search surface</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-primary/10 p-3">category</span><span className="rounded-lg bg-amber/10 p-3">product</span><span className="rounded-lg bg-mint/10 p-3">guide</span></div><p className="mt-4 text-xs text-fg-faint">Coordinated, not duplicated.</p></div>}/>
 <PublicSection><PublicHeading eyebrow="Commerce priorities" title="Protect the catalog while creating useful demand."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={Tags} title="Category quality" body="Align category purpose, copy, filters, canonicals and internal links without forcing text onto every template."/><PublicCard icon={Network} title="Index controls" body="Model faceted URLs, duplication, sitemaps and crawl paths before proposing scalable page systems."/><PublicCard icon={ShoppingBag} title="Revenue context" body="Connect authorized commerce analytics while separating correlation, assisted journeys and direct organic outcomes."/></div></PublicSection>
 <PublicSection muted><div className="grid gap-7 lg:grid-cols-2"><div><PublicHeading eyebrow="Launch gate" title="Scale only after the sample passes."/><PublicChecklist items={["Each page class serves a distinct customer task","Source data is accurate and sufficiently complete","Templates produce materially useful variation","Canonical and noindex rules are intentional","Internal links help discovery and shopping","A bounded cohort is inspected before expansion"]}/></div><PublicCard title="Seasonal and inventory reality" body="Stock, price, assortment and seasonality can invalidate content quickly. Use current authorized commerce data and define what happens when products disappear." tone="amber"/></div></PublicSection>
 <PublicFaq items={[["Will SEOForge generate thousands of product descriptions?","Not without source quality, uniqueness, page purpose and controlled rollout gates. Scale is not treated as value by itself."],["Can it guarantee organic revenue?","No. It can measure authorized analytics and commerce observations, but cannot guarantee search visibility or purchases."],["Can I connect my store free?","No. Provider and production access require a paid workspace."]]}/><PublicCta title="Operate ecommerce search growth with catalog-aware safeguards." body="Choose paid capacity or book a walkthrough for your platform and URL surface."/>
</PublicShell>}
