import type { Metadata } from "next";
import { Activity, Link2, Radar, RefreshCw, ScanSearch, ShieldAlert } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Continuous Search Optimization — SEOForge", description: "Monitor rankings, technical health, content decay, links, competitors and backlinks, then prepare measurable production changes.", alternates: { canonical: "/platform/search-optimization" } };

export default function SearchOptimizationPage() {
  return <PublicShell>
    <PublicHero eyebrow="Search Optimization pipeline" title="Your existing content should never be left to decay." description="SEOForge continuously watches the pages you already own, separates meaningful change from noise and prepares the exact technical or editorial improvement for human approval." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="See the Workflow" secondaryHref="/how-it-works" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Priority findings</p><div className="mt-4 space-y-3">{[["/guides/oauth","Decay confirmed","refresh"],["/docs/tokens","3 orphaned routes","links"],["/compare/auth","Intent overlap","consolidate"]].map(([p,s,a])=><div key={p} className="rounded-xl border border-edge p-4"><div className="flex justify-between text-xs"><b>{p}</b><span className="text-primary">{a}</span></div><p className="mt-2 text-[10px] text-fg-faint">{s}</p></div>)}</div></div>} />
    <PublicSection><PublicHeading eyebrow="Continuous detection" title="One queue for the changes your existing library needs."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><PublicCard icon={Activity} title="Rank and SERP movement" body="Market, device, engine and SERP-feature observations carry deployment annotations."/><PublicCard icon={ShieldAlert} tone="rose" title="Technical health" body="Crawlability, canonicals, redirects, schema, sitemaps, links and performance."/><PublicCard icon={RefreshCw} tone="amber" title="Decay and refresh" body="Sustained losses are diagnosed before a targeted update or consolidation is proposed."/><PublicCard icon={ScanSearch} tone="mint" title="Intent overlap" body="Cannibalization findings distinguish shared keywords from genuinely conflicting pages."/><PublicCard icon={Link2} title="Link graph" body="Internal-link changes improve discovery and navigation without forced anchors."/><PublicCard icon={Radar} tone="amber" title="Market context" body="Competitors, backlinks and AI-citation probes inform decisions without becoming causal claims."/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Optimization loop" title="Detection is useful only when it reaches a measured conclusion."/><div className="mt-10"><PublicSteps steps={["Monitor authorized search, analytics, crawl and market evidence","Confirm the signal across a meaningful window","Prioritize impact, confidence, effort, risk and active conflicts","Prepare the exact content, link, metadata or code change","Validate and route the proposal to a human reviewer","Publish approved work, verify production and annotate the baseline","Observe the chosen metric; keep, iterate or propose rollback"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Example proposal" title="A specific refresh with a specific reason."/><PublicChecklist items={["Before: /guides/oauth lost 31% non-brand clicks over 12 weeks","Diagnosis: SERP intent shifted toward implementation decisions; impressions remained available","Change: replace generic intro, add decision table, update two outdated examples and link three relevant docs","Approval: content diff, sources, preview, risk and rollback commit","Measurement: 28-day query cohort, qualified docs progression and conversion observation"]}/></div><div className="marketing-card p-6 font-mono text-[11px]"><p className="text-fg-faint">OPT-731 · refresh proposal</p><p className="mt-4 rounded bg-rose/8 p-3 text-rose">- OAuth is an industry-standard protocol...</p><p className="mt-2 rounded bg-mint/8 p-3 text-mint">+ Use OAuth when a person delegates access; use a scoped service token for bounded server jobs.</p><p className="mt-3 text-amber">approval required · rollback ready</p></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-5 lg:grid-cols-3"><PublicCard title="Human authority" body="Every proposed diff, merge, redirect or CMS update requires explicit approval."/><PublicCard title="Connected evidence" body="Search Console, GA4, supported rank providers, GitHub and WordPress remain permission scoped."/><PublicCard title="Plan capacity" body="Plans define sites, tracked queries, monitoring cadence, execution and concurrency—not guaranteed outcomes."/></div></PublicSection>
    <PublicFaq items={[["Is this a one-time SEO audit?","No. Monitoring, diagnosis, implementation and measurement repeat as evidence changes."],["Does every ranking drop trigger an edit?","No. Noise, seasonality, tracking changes and weak evidence can result in observation rather than action."],["Can SEOForge publish fixes automatically?","No. Every production proposal needs explicit human approval."],["How are results attributed?","The system records the baseline, deployment annotation, cohort, observation window and known confounders."],["Does optimization guarantee recovery?","No. Search engines control rankings; SEOForge improves controllable inputs and measures outcomes."]]}/>
    <PublicCta title="Protect and compound the value of every page you already own." body="Choose a paid optimization plan with the tracked-query and operating capacity your site requires."/>
  </PublicShell>;
}

