import type { Metadata } from "next";
import { BookOpenCheck, FileOutput, Quote, Workflow } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Evidence-Backed Article Generation — SEOForge", description: "Create source-backed, brand-aligned articles that arrive as reviewable website-native publishing proposals.", alternates: { canonical: "/platform/content-growth/article-generation" } };

export default function ArticleGenerationPage() {
  return <PublicShell>
    <PublicHero eyebrow="Article generation" title="Generate the finished article—sources, structure, links and production context included." description="SEOForge drafts from an approved brief and source map, preserves claim-level support, matches your brand rules and prepares the article in the format your real website expects." primary="Choose a Content Plan" primaryHref="/pricing" secondary="Review Editorial Controls" secondaryHref="/platform/content-growth/editorial-review" visual={<div className="marketing-card overflow-hidden"><div className="border-b border-edge p-5"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Draft artifact · oauth-vs-api-keys.mdx</p><p className="mt-2 text-sm font-semibold">OAuth vs API keys: choosing an access model</p></div><div className="space-y-3 p-5 text-xs leading-5"><p className="rounded-lg bg-panel p-3"><b>Direct answer</b><br/>Use OAuth when a user delegates access; use scoped keys for bounded machine-to-machine jobs.</p><p className="rounded-lg border border-edge p-3 text-fg-mute">6 verified sources · 4 internal links · FAQ schema · 1 decision diagram</p><p className="text-amber">Status: editorial review required</p></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Approved input" title="Drafting starts after the editorial decision is clear."/><PublicChecklist items={["Audience: engineering leads selecting an authentication model","Intent: compare tradeoffs and choose an implementation path","Required claims: delegation, rotation, scopes and revocation","Approved sources: standards, provider documentation and internal product docs","Conversion purpose: continue to implementation documentation","Excluded claims: “most secure,” unsupported benchmarks and rank promises"]}/></div><div><PublicHeading eyebrow="Finished output" title="A complete, website-ready article package."/><PublicChecklist items={["Answer-first introduction and scannable decision criteria","Source-linked factual claims and explicit uncertainty","Original examples instead of competitor paraphrases","Contextual internal links with natural anchor copy","Metadata, structured-data fields and accessibility notes","MDX, CMS blocks or repository-native content plus preview"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Draft workflow" title="Generation is one stage inside a governed pipeline."/><div className="mt-10"><PublicSteps steps={["Lock the approved brief, source set and prohibited claims","Retrieve only relevant site voice and product context","Draft the answer architecture before expanding sections","Attach support to factual claims and flag unresolved evidence","Add internal links, conversion path and article-native media slots","Run editorial review, production validation and human approval"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Quote} title="Claim ledger" body="Every consequential fact points to an approved source or a visible review flag."/><PublicCard icon={BookOpenCheck} tone="mint" title="Brand rules" body="Voice, audience, terminology and prohibited claims remain attached to the draft."/><PublicCard icon={Workflow} tone="amber" title="Site context" body="Internal links and conversion paths serve the existing information architecture."/><PublicCard icon={FileOutput} tone="rose" title="Production file" body="Review the actual MDX, CMS blocks, metadata and preview—not a text export."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><PublicHeading eyebrow="Human review" title="Editors can change the article without surrendering control."/><p className="mt-5 text-sm leading-6 text-fg-mute">A reviewer sees sources, flagged claims, content diff, link targets, media and preview. Approval applies to this proposal only; revisions return it to review.</p></div><div className="marketing-card p-6"><p className="text-sm font-semibold">Capacity and measurement</p><p className="mt-3 text-sm leading-6 text-fg-mute">Article and model usage is bounded by the paid plan. Published work is annotated and measured for qualified visibility, engagement and conversions; SEOForge never represents a draft as a customer result.</p></div></div></PublicSection>
    <PublicFaq items={[["Does the agent browse and cite sources?","It builds an approved source map and keeps support attached to factual claims for editorial verification."],["Can it write in our voice?","Brand rules and approved examples guide the draft, while a human editor confirms the result."],["Will it rewrite competitor articles?","No. Competitors can inform market context, but the article must have original structure, examples and purpose."],["What exactly gets approved?","The article, sources, media, metadata, internal links, production diff and preview."],["Does article generation guarantee organic traffic?","No. SEOForge prepares and measures strong work, but cannot guarantee search-engine distribution."]]}/>
    <PublicCta title="Produce articles that are ready for editorial and production review." body="Choose a paid plan to connect approved briefs with your website-native content pipeline."/>
  </PublicShell>;
}
