import type { Metadata } from "next";
import { Activity, GitBranch, Radar, Sparkles } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "The Four SEOForge Agents", description: "Meet the four accountable agents that coordinate content growth, search optimization and website-native delivery under human authority.", alternates: { canonical: "/agents" } };

export default function AgentsPage() {
  return <PublicShell>
    <PublicHero eyebrow="The autonomous team" title="Four agents with clear jobs, bounded tools and visible handoffs." description="The SEOForge team is designed like an operating system: the Supervisor controls priorities and capacity, two specialist pipelines investigate and prepare work, and the Site Experience Engineer turns approvals into validated site-native proposals." primary="Deploy Your SEO Team" primaryHref="/pricing" secondary="See the Workflow" secondaryHref="/how-it-works" visual={<div className="relative marketing-card p-6"><div className="mx-auto w-fit rounded-2xl border border-primary/30 bg-primary/10 px-5 py-4 text-center"><p className="text-[10px] text-primary">01</p><p className="mt-1 text-sm font-semibold">Workflow Supervisor</p></div><div className="mx-auto h-8 w-px bg-edge-2"/><div className="grid grid-cols-2 gap-4"><div className="rounded-xl border border-mint/25 bg-mint/8 p-4 text-center text-xs">02<br/><b>Content Growth</b></div><div className="rounded-xl border border-amber/25 bg-amber/8 p-4 text-center text-xs">03<br/><b>Search Optimization</b></div></div><div className="mx-auto h-8 w-px bg-edge-2"/><div className="mx-auto w-fit rounded-xl border border-rose/25 bg-rose/8 px-5 py-3 text-center text-xs">04 · <b>Site Experience Engineer</b></div><p className="mt-5 text-center text-[10px] text-fg-faint">Every production path ends at human approval</p></div>} />
    <PublicSection><PublicHeading eyebrow="Agent responsibilities" title="Different specialists create different artifacts."/><div className="mt-10 grid gap-5 md:grid-cols-2"><PublicCard icon={Activity} title="01 · Workflow Supervisor" body="Owns queues, schedules, budgets, heartbeats, conflict resolution, retries and approval state. Finished artifact: an auditable assignment and execution ledger."/><PublicCard icon={Sparkles} tone="mint" title="02 · Content Growth Agent" body="Owns opportunities, gaps, calendars, briefs, articles, editorial checks, media and conversion purpose. Finished artifact: a complete article package."/><PublicCard icon={Radar} tone="amber" title="03 · Search Optimization Agent" body="Owns rankings, technical health, decay, refreshes, cannibalization, links, competitors and backlinks. Finished artifact: an evidence-backed optimization proposal."/><PublicCard icon={GitBranch} tone="rose" title="04 · Site Experience Engineer" body="Owns framework and theme understanding, code or CMS diffs, builds, screenshots and rollback context. Finished artifact: a validated production proposal."/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Real handoff" title="One decaying guide moves through accountable owners."/><div className="mt-10"><PublicSteps steps={["Supervisor detects a priority signal and reserves a bounded run","Search Optimization verifies a sustained intent and CTR change","Content Growth supplies new source and answer-structure context if needed","Site Experience prepares the exact MDX, metadata and internal-link diff","Human reviewer accepts, edits or rejects the production proposal","Validation records deployment health and starts the observation window"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Operational transparency" title="See what happened without pretending a model’s hidden reasoning is proof."/><PublicChecklist items={["Assignment, objective, owner and allowed tools","Evidence URLs, provider observations and timestamps","Costs, reserved capacity, retries and terminal state","Artifact diff, preview, validation and rollback context","Human decision and post-deploy measurement annotation"]}/></div><div className="marketing-card p-6"><p className="text-sm font-semibold">Paid capacity, same integrity</p><p className="mt-3 text-sm leading-6 text-fg-mute">Every plan includes the four-agent operating model and human production boundary. Plans vary sites, tracked queries, content, media, concurrency and developer access.</p><p className="mt-5 rounded-lg border border-amber/25 bg-amber/8 p-4 text-xs leading-5 text-amber">Agents cannot self-approve, retrieve credentials, bypass branch protection or promise search outcomes.</p></div></div></PublicSection>
    <PublicFaq items={[["Are these general-purpose chatbots?","No. Each agent has a bounded operational role, structured artifacts, scoped tools and explicit handoffs."],["Can one agent publish another agent’s work?","No. Production approval remains a separate authenticated human action."],["What if two agents want to change one page?","The Supervisor identifies overlapping scope, serializes or merges the work and preserves one reviewable proposal."],["Do I receive all four agents on Starter?","Yes. Plans change operating capacity, not the core safety model."],["Do the agents guarantee rankings?","No. They prepare and measure controlled improvements; search engines determine distribution."]]}/>
    <PublicCta title="Deploy the complete team—not a disconnected set of AI tools." body="Choose a paid plan, connect scoped providers and keep explicit authority over every production change."/>
  </PublicShell>;
}
