import type { Metadata } from "next";
import { BookOpenCheck, CalendarDays, Repeat2 } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"SEOForge vs Frase — Fair Comparison (July 2026)",description:"Compare continuous site operations with research, briefing and content optimization workflows.",alternates:{canonical:"/seoforge-vs-frase"}};
export default function SeoForgeVsFrasePage(){return <PublicShell>
 <PublicHero eyebrow="Vendor-authored comparison · 20 July 2026" title="SEOForge vs Frase: continuous operating loop or focused content workspace?" description="SEOForge coordinates monitoring, creation, optimization, governed delivery and measurement. Frase is broadly associated with content research and optimization. The better fit depends on where your workflow currently breaks." primary="Choose SEOForge" primaryHref="/pricing" secondary="Read Full Comparison" secondaryHref="/compare/frase" visual={<div className="marketing-card p-7"><CalendarDays className="text-primary"/><p className="mt-5 font-semibold">Test two assignments</p><PublicChecklist items={["One net-new implementation guide","One decaying page refresh","The same sources and constraints","The same production destination"]}/></div>}/>
 <PublicSection><PublicHeading eyebrow="Fit" title="A focused editor can be the more efficient choice."/><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={Repeat2} title="SEOForge may fit"><PublicChecklist items={["Recurring site monitoring must create prioritized work","Multiple agents need bounded, visible handoffs","Production delivery and outcome measurement are in scope"]}/></PublicCard><PublicCard icon={BookOpenCheck} title="Frase may fit better" tone="amber"><PublicChecklist items={["Research, briefing and individual-page optimization are the bottleneck","Editors want a focused hands-on workspace","Publishing and operational governance already work well"]}/></PublicCard></div><p className="mt-8 text-sm leading-6 text-fg-mute">SEOForge authored this comparison. Confirm Frase’s current capabilities and commercial terms with Frase. No unsupported competitor limitation, private capability or customer outcome is presented.</p></PublicSection>
 <PublicFaq items={[["Is SEOForge an editor?","Editing is one stage; SEOForge’s intended scope is the continuous site-wide operating loop."],["Is Frase limited to briefs?","We do not make that claim. Verify its current feature set directly."],["Can I use SEOForge before subscribing?","Public pages and demos are available, but product access is paid."]]}/><PublicCta title="Choose the operating loop when the bottleneck surrounds the editor." body="Review paid SEOForge capacity for your sites and workflows."/>
</PublicShell>}
