import type { Metadata } from "next";
import Link from "next/link";
import { Scale, CalendarDays, Layers3, ShieldCheck } from "lucide-react";
import { PublicCard, PublicCta, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "SEO Software Comparisons — SEOForge", description: "Dated, vendor-authored comparisons of SEOForge and other operating models.", alternates: { canonical: "/compare" } };

export default function ComparePage() {
  return <PublicShell>
    <PublicHero eyebrow="Vendor-authored comparisons" title="Compare the operating model, not a cherry-picked feature grid." description="These pages explain what SEOForge is built to do, where focused tools may fit better, and which responsibilities still stay with your team. Every comparison states its review date and avoids unsupported claims." primary="See How SEOForge Works" primaryHref="/how-it-works" secondary="View Pricing" secondaryHref="/pricing" visual={<div className="marketing-card p-7"><Scale className="text-primary" /><p className="mt-5 text-sm font-semibold">Our comparison standard</p><ul className="mt-5 space-y-3 text-sm text-fg-mute"><li>• Vendor-authored and visibly dated</li><li>• Official public information only</li><li>• Competitor-fit scenarios included</li><li>• Capabilities rechecked before buying</li></ul></div>} />
    <PublicSection><PublicHeading eyebrow="Choose a comparison" title="Four focused platforms, considered on their own terms." body="Reviewed 20 July 2026. Product capabilities and pricing change; verify current details with each vendor." /><div className="mt-10 grid gap-4 md:grid-cols-2"><PublicCard icon={Layers3} title="SEOForge vs Surfer SEO" body="Continuous multi-agent production operations compared with a focused content optimization workflow."><Link className="mt-5 inline-block text-sm font-semibold text-primary" href="/compare/surfer-seo">Read comparison →</Link></PublicCard><PublicCard icon={Layers3} title="SEOForge vs Search Atlas" body="A production-governed autonomous system compared with a broader SEO software suite."><Link className="mt-5 inline-block text-sm font-semibold text-primary" href="/compare/search-atlas">Read comparison →</Link></PublicCard><PublicCard icon={Layers3} title="SEOForge vs Jasper" body="Search operations and governed publishing compared with general AI marketing content creation."><Link className="mt-5 inline-block text-sm font-semibold text-primary" href="/compare/jasper">Read comparison →</Link></PublicCard><PublicCard icon={Layers3} title="SEOForge vs Frase" body="Continuous site operations compared with research, briefing and content optimization workflows."><Link className="mt-5 inline-block text-sm font-semibold text-primary" href="/compare/frase">Read comparison →</Link></PublicCard></div></PublicSection>
    <PublicSection muted><div className="grid gap-4 md:grid-cols-3"><PublicCard icon={CalendarDays} title="Date the evidence" body="We label the review date and separate confirmed public facts from our interpretation." /><PublicCard icon={Scale} title="Show the tradeoff" body="A comparison is useful only when it says who should not choose SEOForge." /><PublicCard icon={ShieldCheck} title="Keep authority visible" body="We compare publishing controls, validation and measurement—not only writing features." /></div></PublicSection>
    <PublicCta title="Decide whether SEOForge matches the work you need operated." body="Review the workflow first, then choose paid capacity or book a product walkthrough. SEOForge provides no free product access." />
  </PublicShell>;
}
