import type { Metadata } from "next";
import { Binoculars, FileSearch, Radar, ShieldQuestion } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Competitor Movement Intelligence — SEOForge", description: "Observe competitor page and SERP changes, separate correlation from evidence and prepare original responses grounded in your audience.", alternates: { canonical: "/platform/search-optimization/competitors" } };

export default function CompetitorsPage() {
  return <PublicShell>
    <PublicHero eyebrow="Competitor intelligence" title="Understand what changed in the market without copying the page that moved." description="SEOForge watches relevant domains, result types and topic coverage, then tests whether a movement exposes a customer need, a format shift or simply noise. Every response must remain original and product-relevant." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="Explore Search Optimization" secondaryHref="/platform/search-optimization" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">SERP movement · “oauth vs api key”</p><div className="mt-5 space-y-3 text-xs"><p className="rounded-xl border border-edge p-4">docs.example <span className="float-right text-mint">+6</span><small className="mt-2 block text-fg-faint">new decision table · updated 9 days ago</small></p><p className="rounded-xl border border-edge p-4">yourdomain <span className="float-right text-rose">−4</span><small className="mt-2 block text-fg-faint">generic intro · no implementation comparison</small></p></div><p className="mt-3 text-[10px] text-amber">Correlation observed; causal claim not established.</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Evidence collected" title="Market context with uncertainty intact."/><PublicChecklist items={["Ranking URL, position, result type and observation timestamp","Visible page structure, update date and relevant content changes","SERP features and intent composition across the cohort","Your page’s evidence, conversion role and production history","Explicit distinction between observed correlation and inferred opportunity"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Before → original response</p><p className="mt-5 text-sm"><b>Before:</b> your guide defines both methods but does not help a reader choose.</p><p className="mt-3 text-sm"><b>Observed:</b> three rising pages added decision-oriented structures.</p><p className="mt-3 text-sm"><b>Proposed:</b> create your own audience-specific tradeoff table using verified product and standards evidence; preserve distinct examples and voice.</p></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Competitor workflow" title="Observe, test relevance, then choose an original response."/><div className="mt-10"><PublicSteps steps={["Define true search competitors by topic and result set","Collect dated ranking, SERP and visible-page observations","Detect material page, format or coverage movement","Compare with your audience, authority and page purpose","Prioritize only defensible gaps or changes","Prepare an original update and measure the target cohort"]} accent="amber"/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Radar} title="Movement" body="Track meaningful changes in relevant result cohorts."/><PublicCard icon={FileSearch} tone="mint" title="Visible evidence" body="Use accessible page facts, dates and structures—never invented intelligence."/><PublicCard icon={ShieldQuestion} tone="amber" title="Causality boundary" body="A competitor change can inspire a test, not prove why rankings moved."/><PublicCard icon={Binoculars} tone="rose" title="Original response" body="Your page must solve your customer’s task with your evidence and voice."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Review cited observations, the inference boundary, original diff and production validation before approval."/><PublicCard title="Capacity and results" body="Competitor domains, cohorts and checks use paid capacity. SEOForge does not invent competitor limitations or claim guaranteed wins."/></div></PublicSection>
    <PublicFaq items={[["How are search competitors chosen?","By overlapping result sets and topic relevance, not only by companies named in a sales battlecard."],["Does SEOForge copy competitor content?","No. It observes public market evidence and requires an original customer-specific response."],["Can it tell why a competitor moved?","It can form an evidence-backed hypothesis, but correlation is not presented as causation."],["What does the human approve?","The sourced finding and the exact original content or site change."],["Will matching a competitor feature improve rankings?","No outcome is guaranteed; relevance and observed results must be measured."]]}/>
    <PublicCta title="Turn competitor movement into better decisions—not imitation." body="Choose a paid plan to monitor relevant markets and prepare evidence-backed original responses."/>
  </PublicShell>;
}

