import type { Metadata } from "next";
import { CalendarDays, FileText, Image, Search, Send, TrendingUp } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Content Growth Pipeline — SEOForge", description: "Turn qualified search opportunities into sourced, website-native, measurable content through a governed paid workflow.", alternates: { canonical: "/platform/content-growth" } };

export default function ContentGrowthPage() {
  return <PublicShell>
    <PublicHero eyebrow="Content Growth pipeline" title="Turn search opportunities into published, measurable content." description="SEOForge connects market research, editorial planning, source-backed drafting, original media and production delivery. Your team reviews the finished article and exact publishing proposal before anything goes live." primary="Choose a Content Plan" primaryHref="/pricing" secondary="Book a Demo" secondaryHref="/demo" visual={<div className="marketing-card p-5"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Opportunity packet · CG-441</p><div className="mt-4 rounded-xl border border-primary/25 bg-primary/8 p-4"><p className="text-sm font-semibold">“OAuth vs API keys”</p><div className="mt-3 grid grid-cols-3 gap-2 text-[10px] text-fg-faint"><span>Intent<br/><b className="text-fg">comparison</b></span><span>Fit<br/><b className="text-fg">high</b></span><span>State<br/><b className="text-amber">planned</b></span></div></div><div className="mt-3 space-y-2 text-xs">{["Brief with 6 verified sources","1,850-word article draft","Decision-tree diagram + social crop","Next.js PR with metadata"].map((x)=><p key={x} className="rounded-lg border border-edge p-3">{x}</p>)}</div></div>} />
    <PublicSection><PublicHeading eyebrow="Example opportunity" title="See the whole packet before approving production." body="The agent does not hand over a keyword list. It assembles the customer question, evidence, editorial decision and production-ready outcome."/><div className="mt-10 grid gap-5 lg:grid-cols-3"><PublicCard icon={Search} title="Input" body="Product: developer identity platform. Audience: engineering leads. Existing authority: authentication and security. Gap: no decision guide for OAuth versus keys."/><PublicCard icon={FileText} tone="mint" title="Finished article" body="A sourced comparison with decision criteria, implementation cautions, internal links, FAQ answers and a product-relevant next step."/><PublicCard icon={Send} tone="amber" title="Publishing proposal" body="A route-native MDX file, metadata, generated diagram, sitemap update, build evidence and preview URL."/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Article lifecycle" title="One governed path from research to observed outcome."/><div className="mt-10"><PublicSteps steps={["Research intent, SERP composition, sources and business relevance","Cluster against existing pages to prevent duplication","Create the brief, outline, source map and conversion purpose","Draft the article and article-native media","Run editorial, brand, accessibility and originality review","Prepare a GitHub or WordPress proposal for human approval","Validate production and observe visibility, engagement and conversions"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><PublicHeading eyebrow="Finished deliverables" title="Every stage creates something reviewable."/><PublicChecklist items={["Opportunity report with intent, evidence, confidence and exclusions","Editorial brief with claims, sources, entities, questions and internal links","Complete article with clearly attributed factual support","Brand-matched hero, explanatory visual and accessibility metadata","Previewable code or CMS proposal with validation and rollback context","Measurement plan with baseline, primary metric and observation window"]}/></div><div className="grid gap-4 sm:grid-cols-2"><PublicCard icon={CalendarDays} title="Calendar" body="Priorities, dependencies, review owners and realistic publication windows."/><PublicCard icon={Image} tone="rose" title="Media" body="Original visuals created for the page’s explanation—not decorative filler."/><PublicCard icon={TrendingUp} tone="mint" title="Measurement" body="Search visibility stays separate from engagement, leads and attributed revenue."/><PublicCard icon={FileText} tone="amber" title="Human review" body="Reviewers approve or reject the complete content, files, preview and risk context."/></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-8 lg:grid-cols-2"><div className="marketing-card p-6"><p className="text-sm font-semibold">Capacity is planned, not unlimited</p><p className="mt-3 text-sm leading-6 text-fg-mute">Starter supports a focused single-site cadence. Growth adds site, article, media and monitoring capacity. Agency adds portfolio controls and higher concurrency. Exact current allowances appear on pricing and in the workspace ledger.</p></div><div className="marketing-card p-6"><p className="text-sm font-semibold">Connected delivery</p><p className="mt-3 text-sm leading-6 text-fg-mute">GitHub or WordPress supplies the publishing destination; Search Console and GA4 supply customer-owned observation. Provider data informs decisions but never becomes a ranking guarantee.</p></div></div></PublicSection>
    <PublicFaq items={[["Does SEOForge create articles automatically?","It can autonomously research and prepare complete articles, but a human must approve every production proposal."],["How do you prevent duplicate topics?","Every opportunity is compared with published pages, scheduled work and active agent assignments before drafting."],["Can it match our brand?","Onboarding captures voice, visual rules, prohibited claims, audience and site patterns; editorial review still confirms the result."],["What counts toward plan capacity?","Research, articles, media, provider usage, tracked queries and agent execution consume the allowances shown for the paid plan."],["Will every article rank?","No. SEOForge selects defensible opportunities, produces strong work and measures outcomes, but search engines decide rankings."]]}/>
    <PublicCta title="Deploy a content pipeline that reaches your real website." body="Choose a paid plan, connect one authorized publishing destination and approve complete article proposals before publication."/>
  </PublicShell>;
}
