import type { Metadata } from "next";
import { CalendarDays, PenTool, Workflow } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"SEOForge vs Surfer SEO — Fair Comparison (July 2026)",description:"Compare SEOForge continuous SEO operations with Surfer SEO content optimization workflows.",alternates:{canonical:"/seoforge-vs-surfer-seo"}};
export default function SeoForgeVsSurferSeoPage(){return <PublicShell>
 <PublicHero eyebrow="Vendor-authored comparison · 20 July 2026" title="SEOForge vs Surfer SEO: operating system or focused content workflow?" description="SEOForge is built to coordinate continuous content creation, site optimization and governed production. Surfer SEO is broadly positioned around content optimization. This page states SEOForge’s perspective; confirm Surfer’s current product directly." primary="Choose SEOForge" primaryHref="/pricing" secondary="Read Full Comparison" secondaryHref="/compare/surfer-seo" visual={<div className="marketing-card p-7"><CalendarDays className="text-primary"/><p className="mt-5 text-sm font-semibold">Decision snapshot</p><div className="mt-4 space-y-3"><p className="rounded-xl bg-primary/10 p-4 text-sm">SEOForge · continuous site operations</p><p className="rounded-xl bg-amber/10 p-4 text-sm">Surfer · focused content optimization</p></div></div>}/>
 <PublicSection><PublicHeading eyebrow="Choose by job" title="Neither operating model is universally better."/><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={Workflow} title="SEOForge may fit"><PublicChecklist items={["Two autonomous pipelines need one accountable Supervisor","Changes must become GitHub or WordPress proposals","Human approval, validation and measurement belong together"]}/></PublicCard><PublicCard icon={PenTool} title="Surfer may fit better" tone="amber"><PublicChecklist items={["Writers primarily need hands-on content optimization","Your team already owns deployment and operational governance","A focused editor complements your existing SEO stack"]}/></PublicCard></div><p className="mt-8 text-sm leading-6 text-fg-mute">Method: SEOForge’s capabilities come from current product specifications. Competitor descriptions are deliberately high-level; no private roadmap, customer result or unsupported limitation is asserted. Recheck official product and pricing information before purchase.</p></PublicSection>
 <PublicFaq items={[["Is this independent?","No. SEOForge authored it and labels the date so buyers can account for that perspective."],["Does SEOForge claim Surfer cannot publish?","No. Verify current features and integrations with Surfer. Our comparison focuses on each product’s broad operating emphasis."],["Can I try SEOForge free?","No. Product access is paid; public workflow education and demos remain available."]]}/><PublicCta title="Choose continuous operations when the work extends beyond the editor." body="Review paid plans or book a product walkthrough."/>
</PublicShell>}
