import type { Metadata } from "next";
import { FileImage, Palette, ScanText, Share2 } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Article-Native Media Generation — SEOForge", description: "Create explanatory diagrams, brand-matched heroes, social crops and accessibility metadata as part of an approved article package.", alternates: { canonical: "/platform/content-growth/media-generation" } };

export default function MediaGenerationPage() {
  return <PublicShell>
    <PublicHero eyebrow="Media generation" title="Create the visual the article needs—not another decorative stock image." description="SEOForge derives a media brief from the approved article, matches your visual system and produces reviewable assets with responsive dimensions, alt text, captions and publishing context." primary="Choose a Content Plan" primaryHref="/pricing" secondary="See Article Generation" secondaryHref="/platform/content-growth/article-generation" visual={<div className="marketing-card p-5"><div className="aspect-[16/9] rounded-xl border border-primary/25 bg-gradient-to-br from-primary/20 via-panel to-mint/10 p-5"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">OAuth decision diagram</p><div className="mt-6 flex items-center justify-between gap-2 text-[10px]"><span className="rounded-lg bg-primary/20 p-3">User delegates?</span><span>→</span><span className="rounded-lg bg-mint/20 p-3">OAuth</span></div><div className="mt-3 flex items-center justify-between gap-2 text-[10px]"><span className="rounded-lg bg-amber/20 p-3">Bounded server job?</span><span>→</span><span className="rounded-lg bg-rose/20 p-3">Scoped key</span></div></div><p className="mt-3 text-[10px] text-fg-faint">1600×900 WebP · 42 KB · alt text drafted</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Media brief input" title="The article determines the visual’s job."/><PublicChecklist items={["Explain when OAuth and API keys fit different access models","Use approved navy, blue and mint tokens with 12px corner radius","Remain legible at 640px and understandable without color","Avoid provider logos, fake UI and unsupported security rankings"]}/></div><div><PublicHeading eyebrow="Finished asset package" title="Production details arrive with the pixels."/><PublicChecklist items={["1600×900 hero WebP and responsive 960×540 derivative","Article decision diagram in approved visual language","1200×630 social preview crop with safe text area","Descriptive alt text and optional explanatory caption","File names, dimensions, compression evidence and insertion points"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Media workflow" title="Visual purpose, brand fit and accessibility are checked separately."/><div className="mt-10"><PublicSteps steps={["Extract the concept that benefits from visual explanation","Write a media brief with audience, hierarchy and constraints","Apply approved design tokens and prohibited visual patterns","Generate purpose-specific variants and responsive crops","Review factual accuracy, legibility, accessibility and file weight","Attach approved assets to the article production proposal"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Palette} title="Theme match" body="Color, typography, spacing, geometry and image treatment follow the site profile."/><PublicCard icon={FileImage} tone="mint" title="Useful variants" body="Hero, inline diagram and social preview each have a defined job."/><PublicCard icon={ScanText} tone="amber" title="Accessibility" body="Meaning, sequence, contrast and alternatives are reviewed before production."/><PublicCard icon={Share2} tone="rose" title="Delivery" body="Optimized assets, paths and article placements land in the same proposal."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Approve, replace or reject each asset alongside its source article. Media approval cannot publish the article or upload to production by itself."/><PublicCard title="Capacity and measurement" body="Media counts against paid plan capacity. Delivery checks file weight and layout stability; page outcomes are measured at article level without claiming an image caused rankings."/></div></PublicSection>
    <PublicFaq items={[["Does every article receive AI-generated art?","No. Media is created only when it explains, demonstrates or packages the article more effectively."],["Can assets match our existing website?","Yes. The agent uses an approved visual profile and site patterns, with human review before production."],["Do you generate fake product screenshots?","No. Product UI must come from authorized real captures or be clearly labeled as an illustrative concept."],["What gets approved?","Each asset, crop, alt text, caption, file path and article placement."],["Will images improve rankings?","Useful, accessible and performant media can improve the page experience, but SEOForge does not guarantee ranking outcomes."]]}/>
    <PublicCta title="Give every important article a purpose-built visual system." body="Choose a paid plan with the media capacity your publishing cadence requires."/>
  </PublicShell>;
}
