import type { Metadata } from "next";
import { BadgeDollarSign, Goal, Route, ShieldCheck } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Content Monetization Workflow — SEOForge", description: "Connect content to qualified product demand, governed affiliate placements and measurable conversions without distorting editorial intent.", alternates: { canonical: "/platform/content-growth/monetization" } };

export default function MonetizationPage() {
  return <PublicShell>
    <PublicHero eyebrow="Content monetization" title="Give every article a business role without turning it into a sales trap." description="SEOForge maps the searcher’s task to an appropriate next step, prepares contextual conversion modules, enforces disclosure rules and measures qualified outcomes separately from traffic." primary="Choose a Content Plan" primaryHref="/pricing" secondary="See the Content Pipeline" secondaryHref="/platform/content-growth" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Conversion map · OAuth comparison</p><div className="mt-5 space-y-3 text-xs"><div className="rounded-xl border border-edge p-4"><span className="text-fg-faint">Reader task</span><p className="mt-2">Choose an authentication model</p></div><div className="text-center text-primary">↓</div><div className="rounded-xl border border-primary/25 bg-primary/8 p-4"><span className="text-fg-faint">Contextual next step</span><p className="mt-2 font-semibold">Read implementation guide</p></div><div className="text-center text-primary">↓</div><div className="rounded-xl border border-mint/25 bg-mint/8 p-4"><span className="text-fg-faint">Measured event</span><p className="mt-2">Qualified docs progression</p></div></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Example input" title="A page should earn the right to ask for action." body="The OAuth comparison serves evaluation intent. A demo wall would interrupt the task, while a relevant implementation guide advances it."/><PublicChecklist items={["Primary job: choose between delegated and machine access","Product connection: scoped credentials and access governance","Allowed CTA: implementation guide; pricing only after product-fit context","Prohibited: fabricated urgency, disguised links and unsupported savings claims"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Finished proposal</p><PublicChecklist items={["Inline decision template after the tradeoff table","Contextual link to authentication implementation docs","End-of-article paid-plan CTA with explicit commercial language","GA4 events for CTA view, docs progression and paid conversion","Affiliate disclosure block only where approved commercial links exist"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Monetization workflow" title="Intent comes before conversion mechanics."/><div className="mt-10"><PublicSteps steps={["Define the article’s audience task and commercial relationship","Map relevant product, lead or governed affiliate outcomes","Choose the least disruptive next step for each content stage","Prepare copy, placement, disclosure and analytics changes","Review editorial integrity and approve the exact production diff","Measure qualified actions, conversions and attributed value"]} accent="amber"/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Goal} title="Purpose" body="The conversion serves the query and article before it serves the funnel."/><PublicCard icon={Route} tone="mint" title="Journey" body="Educational, comparison and high-intent pages use different next steps."/><PublicCard icon={ShieldCheck} tone="amber" title="Governance" body="Disclosures, claims and affiliate policies remain explicit and reviewable."/><PublicCard icon={BadgeDollarSign} tone="rose" title="Measurement" body="Traffic, qualified progression, leads and revenue remain separate metrics."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human approval" body="A reviewer approves the CTA copy, destination, placement, disclosure, analytics event and page diff. Agents cannot activate commercial links independently."/><PublicCard title="Plan boundary" body="Conversion analysis and content production consume paid capacity. SEOForge reports observed attribution with its window and model; it never invents revenue proof."/></div></PublicSection>
    <PublicFaq items={[["Does SEOForge force a CTA into every article?","No. The next step must be relevant to the reader’s task; some pages should simply lead to another useful resource."],["Can it manage affiliate content?","It can prepare governed placements when the workspace supplies approved programs, destinations and disclosure rules."],["How is revenue attributed?","Through authorized analytics events and the customer’s declared attribution model and window, with limitations visible."],["What does the reviewer approve?","Copy, destination, placement, disclosure, tracking and the exact production change."],["Does SEOForge guarantee ROI?","No. It improves and measures controllable conversion paths but cannot promise traffic, leads or revenue."]]}/>
    <PublicCta title="Connect useful content to measurable business outcomes." body="Choose a paid plan to add governed conversion design and observation to your content operation."/>
  </PublicShell>;
}

