import type { Metadata } from "next";
import { FileCheck2, GitPullRequest, SearchCheck } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";
export const metadata: Metadata = { title: "SEO Content Automation Software — SEOForge", description: "Automate research, briefs, articles, approval-ready production proposals and measurement.", alternates: { canonical: "/seo-content-automation-software" } };
export default function SeoContentAutomationSoftwarePage(){return <PublicShell>
  <PublicHero eyebrow="SEO content automation software" title="Automation is only useful when the content reaches production safely." description="SEOForge turns qualified search opportunities into source-backed briefs, website-native articles, original media and validated GitHub or WordPress proposals. A human reviews the exact change before anything publishes." primary="Choose Your Plan" primaryHref="/pricing" secondary="See the Content Pipeline" secondaryHref="/platform/content-growth" visual={<div className="marketing-card p-7"><SearchCheck className="text-primary"/><p className="mt-5 text-sm font-semibold">Opportunity → approved production proposal</p><PublicChecklist items={["Intent and evidence captured","Editorial constraints applied","Site-native implementation prepared","Outcome observation scheduled"]}/></div>}/>
  <PublicSection><PublicHeading eyebrow="Complete workflow" title="Replace disconnected generation with accountable production."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={SearchCheck} title="Qualify demand" body="Score intent, business value, competition, current coverage and realistic authority before assigning an article."/><PublicCard icon={FileCheck2} title="Build the artifact" body="Prepare the brief, sources, draft, internal-link plan, media and editorial checks as one reviewable package."/><PublicCard icon={GitPullRequest} title="Deliver and measure" body="Validate the repository or WordPress proposal, await approval, then annotate the deployment and observe results."/></div></PublicSection>
  <PublicSection muted><PublicHeading eyebrow="Operating sequence" title="Every stage has evidence and an owner."/><div className="mt-9"><PublicSteps steps={["Detect an evidence-backed opportunity","Create a brief with sources and conversion purpose","Draft and run editorial integrity checks","Prepare the website-native change and preview","Require authenticated human approval","Validate production and measure the observation window"]}/></div></PublicSection>
  <PublicFaq items={[["Does SEOForge publish automatically?","No. It can automate investigation and preparation, but only an authenticated human can approve the exact production proposal."],["Is this a free article generator?","No. SEOForge is a paid operating platform, not a free writing tool."],["Does generated content guarantee traffic?","No. Search outcomes remain uncertain; SEOForge records baselines and measures approved changes without guarantees."]]}/>
  <PublicCta title="Deploy a content system that owns the work after the draft." body="Choose paid capacity for your sites, publishing volume and approval workflow."/>
</PublicShell>}
