"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Check, ShieldCheck } from "lucide-react";

const plans = [
  { key:"starter", name:"Starter", monthly:149, sites:1, queries:"100", articles:"4", optimizations:"8", media:"20 images", concurrency:"1 active run", note:"One focused website" },
  { key:"growth", name:"Growth", monthly:399, sites:3, queries:"500", articles:"12", optimizations:"30", media:"75 images", concurrency:"3 active runs", note:"A serious growth program" },
  { key:"agency", name:"Agency", monthly:999, sites:10, queries:"2,000", articles:"40", optimizations:"100", media:"250 images", concurrency:"8 active runs", note:"Client and portfolio operations" },
] as const;

export default function PricingExperience() {
  const [annual, setAnnual] = useState(false);
  const [sites, setSites] = useState("1");
  const [objective, setObjective] = useState("both");
  const recommended = useMemo(() => sites === "10+" ? "Agency" : sites === "2-3" || objective === "portfolio" ? "Growth" : "Starter", [sites, objective]);
  return <>
    <div className="flex justify-center"><div className="inline-flex rounded-xl border border-edge bg-panel p-1" role="group" aria-label="Billing cadence"><button onClick={()=>setAnnual(false)} className={`rounded-lg px-4 py-2 text-xs ${!annual?"bg-primary text-white":"text-fg-mute"}`}>Monthly</button><button onClick={()=>setAnnual(true)} className={`rounded-lg px-4 py-2 text-xs ${annual?"bg-primary text-white":"text-fg-mute"}`}>Annual · 2 months included</button></div></div>
    <div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map(plan=>{const price=annual?Math.round(plan.monthly*10/12):plan.monthly;return <article key={plan.key} className={`marketing-card flex flex-col p-7 ${plan.name==="Growth"?"border-primary/60 shadow-[0_0_55px_-28px_rgba(59,130,246,.9)]":""}`}>{plan.name==="Growth"?<span className="mb-5 w-fit rounded-full bg-primary/12 px-3 py-1 text-[10px] font-semibold uppercase tracking-[.15em] text-primary">Recommended</span>:null}<h2 className="text-2xl font-semibold">{plan.name}</h2><p className="mt-2 text-sm text-fg-mute">{plan.note}</p><p className="display mt-7 text-5xl font-semibold">${price}<span className="text-sm font-normal text-fg-faint">/mo</span></p>{annual?<p className="mt-2 text-xs text-mint">${plan.monthly*10} billed annually</p>:<p className="mt-2 text-xs text-fg-faint">Billed monthly</p>}<ul className="mt-8 flex-1 space-y-3 text-sm text-fg-mute">{[`${plan.sites} production site${plan.sites>1?"s":""}`,`${plan.queries} tracked queries`,`${plan.articles} article proposals/month`,`${plan.optimizations} optimization proposals/month`,plan.media,plan.concurrency,"All four agents","Both autonomous pipelines","Human production approval"].map(item=><li key={item} className="flex gap-3"><Check size={15} className="mt-0.5 shrink-0 text-mint"/>{item}</li>)}</ul><Link href={`/sign-up?plan=${plan.key}&billing=${annual?"annual":"monthly"}`} className={`marketing-button mt-8 w-full ${plan.name==="Growth"?"marketing-button-primary":"marketing-button-secondary"}`}>Choose {plan.name}</Link><p className="mt-4 text-center text-[10px] text-fg-faint">Paid activation · cancel renewal from billing portal</p></article>})}</div>
    <div className="mt-16 grid gap-6 rounded-2xl border border-edge bg-panel p-6 sm:p-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Plan recommendation</p><h2 className="mt-4 text-2xl font-semibold">Which operating capacity fits?</h2><p className="mt-3 text-sm leading-6 text-fg-mute">This recommendation changes the plan—not the four-agent safety model.</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-fg-mute">Number of websites<select value={sites} onChange={e=>setSites(e.target.value)} className="mt-2 w-full rounded-lg border border-edge bg-ink px-3 py-3 text-sm text-fg"><option>1</option><option>2-3</option><option>10+</option></select></label><label className="text-xs text-fg-mute">Primary objective<select value={objective} onChange={e=>setObjective(e.target.value)} className="mt-2 w-full rounded-lg border border-edge bg-ink px-3 py-3 text-sm text-fg"><option value="both">Create and optimize</option><option value="content">Create content</option><option value="optimization">Optimize existing pages</option><option value="portfolio">Manage a portfolio</option></select></label><div className="sm:col-span-2 rounded-xl border border-primary/25 bg-primary/8 p-5"><p className="text-[10px] uppercase tracking-[.16em] text-fg-faint">Recommended starting point</p><p className="mt-2 text-xl font-semibold text-primary">{recommended}</p></div></div></div>
    <div className="mt-6 flex items-start gap-3 rounded-xl border border-amber/25 bg-amber/8 p-5 text-sm text-fg-mute"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-amber"/><p>Overages are disabled by default. SEOForge reserves capacity before a run and stops safely at the workspace limit. You can approve optional overages later; model-token mechanics are never exposed as a confusing customer bill.</p></div>
  </>;
}
