import type { Metadata } from "next";
import { Boxes, LineChart, Route } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"SEO Automation for SaaS Companies — SEOForge",description:"Coordinate SaaS category, use-case, comparison, integration and educational content with continuous optimization.",alternates:{canonical:"/seo-automation-for-saas"}};
export default function SeoAutomationForSaasPage(){return <PublicShell>
 <PublicHero eyebrow="SEO automation for SaaS" title="Build the buyer’s search journey without turning it into a page factory." description="SEOForge coordinates product categories, use cases, integrations, comparisons and education around real customer tasks, then continuously monitors the pages that already influence pipeline." primary="Deploy My SEO Team" primaryHref="/pricing" secondary="Book a SaaS Walkthrough" secondaryHref="/demo" visual={<div className="marketing-card p-7"><Route className="text-primary"/><p className="mt-5 font-semibold">Problem → solution → evaluation → action</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><span className="rounded-lg bg-panel-2 p-3">use cases</span><span className="rounded-lg bg-panel-2 p-3">integrations</span><span className="rounded-lg bg-panel-2 p-3">comparisons</span><span className="rounded-lg bg-panel-2 p-3">guides</span></div></div>}/>
 <PublicSection><PublicHeading eyebrow="SaaS operating model" title="Connect search demand to product truth and qualified action."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={Boxes} title="Architecture with purpose" body="Map categories and clusters to buyer tasks, product capabilities and the information needed at each evaluation stage."/><PublicCard icon={Route} title="Evidence-backed production" body="Use product sources, subject-matter review and website-native proposals to avoid invented capabilities."/><PublicCard icon={LineChart} title="Pipeline-aware measurement" body="Observe qualified conversions and assisted journeys without pretending every organic visit equals revenue."/></div></PublicSection>
 <PublicSection muted><div className="grid gap-7 lg:grid-cols-2"><div><PublicHeading eyebrow="Quality gates" title="Every SaaS page must earn its place."/><PublicChecklist items={["Distinct search and buyer purpose","Accurate product capability and limitation","Useful example or implementation detail","Natural relationship to adjacent pages","Clear conversion action appropriate to intent","Baseline and post-deployment observation window"]}/></div><PublicCard title="What SEOForge will not do" body="It will not invent customer proof, publish fake comparisons, create thousands of thin permutations or claim features that product evidence does not support." tone="rose"/></div></PublicSection>
 <PublicFaq items={[["Can SEOForge create comparison pages?","Yes, as vendor-authored, dated and fair pages that show competitor-fit scenarios and avoid unsupported claims."],["Can it connect organic work to conversions?","With authorized analytics, it can observe landing-page and conversion events while preserving attribution limitations."],["Is onboarding free?","No. Site connection and baseline work begin within a paid plan."]]}/><PublicCta title="Give SaaS search growth a continuous operating system." body="Choose paid capacity or book a walkthrough with your product architecture and funnel."/>
</PublicShell>}
