import type { Metadata } from "next";
import { Camera, Code2, GitPullRequest, Palette } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Site Experience Engineer Agent — SEOForge", description: "Meet the agent that understands frameworks and themes, prepares site-native diffs, runs builds, captures screenshots and documents rollback.", alternates: { canonical: "/agents/site-experience-engineer" } };

export default function SiteExperienceEngineerAgentPage() {
  return <PublicShell>
    <PublicHero eyebrow="Agent 04 · Site Experience Engineer" title="The specialist that carries approved SEO work into real website code." description="This agent translates approved content and optimization artifacts into the customer’s framework, theme and publishing model, then proves the proposal with builds, screenshots and rollback instructions." primary="Choose a Publishing Plan" primaryHref="/pricing" secondary="See the Delivery Layer" secondaryHref="/platform/site-experience-engineer" visual={<div className="marketing-card p-5 font-mono text-[10px]"><p className="text-fg-faint">HANDOFF SITE-208</p><p className="mt-4 text-mint">framework · Next.js App Router</p><p className="mt-2 text-mint">theme · tokens matched</p><p className="mt-2 text-primary">files · 4 changed</p><p className="mt-2 text-primary">screenshots · desktop + mobile</p><p className="mt-2 text-amber">state · human approval</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Handoff input" title="An approved artifact plus the site’s real constraints."/><PublicChecklist items={["Approved article or optimization proposal version","Repository or WordPress structure and scoped authorization","Framework, theme, components and content model","Build, preview, branch protection and publishing rules","Affected URLs, validation criteria and rollback expectation"]}/></div><div><PublicHeading eyebrow="Finished output" title="A validated production proposal."/><PublicChecklist items={["Exact code, content, media, metadata and link diff","Website-native components and theme-matched presentation","Typecheck, build, schema and broken-link results","Desktop and mobile screenshots of affected routes","Revert commit or CMS revision with verification steps"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Agent workflow" title="Understand the site before touching the artifact."/><div className="mt-10"><PublicSteps steps={["Profile framework, theme, routes and publishing conventions","Map approved work to site-native files or CMS fields","Create an isolated branch or draft revision","Implement the bounded diff and optimized media","Run build, link, schema and responsive validation","Attach screenshots and rollback; route to human approval"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Code2} title="Framework" body="Routes, content source and build behavior define implementation."/><PublicCard icon={Palette} tone="mint" title="Theme" body="Existing tokens and components define visual fit."/><PublicCard icon={Camera} tone="amber" title="Proof" body="Build evidence and responsive screenshots expose the result."/><PublicCard icon={GitPullRequest} tone="rose" title="Protected handoff" body="The proposal stops before merge, deploy or publication."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="The reviewer inspects exact files, rendered previews, checks, residual risk and rollback before protected production action."/><PublicCard title="Paid capacity" body="Sites, concurrent changes and execution consume plan capacity. Unsupported or failing implementations remain blocked."/></div></PublicSection>
    <PublicFaq items={[["Can it work with an unfamiliar framework?","It profiles the authorized site first; unsupported conventions stay blocked and visible."],["How is theme matching reviewed?","The proposal attaches desktop and mobile screenshots using existing tokens and components."],["What if the build fails?","The work cannot be marked production-ready; logs and failing checks remain attached."],["Can it merge or publish?","No. Protected production authority remains human."],["Does a correct build guarantee SEO results?","No. It proves implementation quality, not search-engine outcomes."]]}/>
    <PublicCta title="Deploy a delivery specialist that respects your real website." body="Choose a paid publishing plan and connect one scoped repository or WordPress destination."/>
  </PublicShell>;
}
