import type { Metadata } from "next";
import { ExternalLink, Link2, SearchX, ShieldAlert } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Backlink Monitoring — SEOForge", description: "Monitor referring domains, anchors, gained and lost links, validate evidence and prepare page or outreach actions without unsupported toxicity labels.", alternates: { canonical: "/platform/search-optimization/backlinks" } };

export default function BacklinksPage() {
  return <PublicShell>
    <PublicHero eyebrow="Backlink monitoring" title="Know which link changed, whether it still exists and what action is justified." description="SEOForge tracks referring pages, targets, anchors and losses, verifies important observations and separates evidence-backed risk signals from simplistic “toxic link” scores." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="Explore Search Optimization" secondaryHref="/platform/search-optimization" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Link change · BL-882</p><div className="mt-5 rounded-xl border border-rose/25 bg-rose/8 p-4 text-xs"><p className="text-rose">Lost referring link</p><p className="mt-3 font-semibold">engineering.example/resources</p><p className="mt-2 text-fg-faint">target now 404 · /guides/api-security-2024</p></div><p className="mt-3 rounded-xl border border-mint/25 bg-mint/8 p-4 text-xs text-mint">Proposal: restore evergreen URL and redirect legacy path</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Evidence collected" title="Provider data is verified before action."/><PublicChecklist items={["Referring URL, target URL, anchor and first/last seen dates","Live status and rendered link verification for priority observations","Target canonical, redirect chain and current content state","Relevant site history: migration, slug change or deleted asset","Risk phrased as observable signals—not unsupported toxicity certainty"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Before → proposed repair</p><p className="mt-5 text-sm"><b>Before:</b> 17 historical referring pages target a retired 2024 guide that now returns 404.</p><p className="mt-3 text-sm"><b>Change:</b> restore an evergreen guide at /guides/api-security and redirect the legacy path after content and intent review.</p><p className="mt-3 text-sm"><b>Measure:</b> live target status, recovered referring links and page cohort visibility.</p></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Backlink workflow" title="Observe, verify, prioritize and repair what you control."/><div className="mt-10"><PublicSteps steps={["Ingest gained, lost and changed referring-link observations","Verify high-impact referring and target pages","Classify migration, content, relationship or evidence-backed risk","Prioritize relevance, target value, confidence and effort","Prepare site repair or human-owned outreach brief","Approve site changes, validate live targets and continue monitoring"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={ExternalLink} title="Referrer evidence" body="Source, anchor, dates and live verification remain attached."/><PublicCard icon={SearchX} tone="rose" title="Lost links" body="Distinguish removed links from broken targets and provider lag."/><PublicCard icon={Link2} tone="mint" title="Target repair" body="Redirect, restore or improve only when the page purpose supports it."/><PublicCard icon={ShieldAlert} tone="amber" title="Risk language" body="Observable patterns stay separate from unsupported penalties or toxicity claims."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Site changes require approval; outreach remains a human-owned communication workflow and is never sent automatically from this page."/><PublicCard title="Capacity and measurement" body="Backlink rows, verification and execution consume paid capacity. SEOForge does not sell links, invent authority metrics or guarantee ranking impact."/></div></PublicSection>
    <PublicFaq items={[["Does SEOForge automatically disavow links?","No. Disavow decisions are high risk and require evidence, expert review and explicit human action."],["What is a toxic backlink?","SEOForge avoids treating a single vendor score as fact; it reports observable relevance, pattern and site evidence."],["Can it send outreach?","This workflow prepares evidence and a brief; external communication requires separate human authorization."],["What gets approved?","Any redirect, restored page, content change or scoped follow-up plan."],["Do recovered links guarantee rankings?","No. Link repair restores a controllable signal; search outcomes remain uncertain."]]}/>
    <PublicCta title="Turn backlink change into verified, controllable action." body="Choose a paid optimization plan with the backlink monitoring and validation capacity your site needs."/>
  </PublicShell>;
}
