import type { Metadata } from "next";
import { Anchor, Link2, Network, Route } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Internal Link Intelligence — SEOForge", description: "Prepare contextual internal links from topic relationships, page roles and rendered link evidence, then validate navigation after deployment.", alternates: { canonical: "/platform/search-optimization/internal-linking" } };

export default function InternalLinkingPage() {
  return <PublicShell>
    <PublicHero eyebrow="Internal linking" title="Add links where they help a reader continue—not where a score wants another anchor." description="SEOForge models page purpose, topic relationships and current navigation, then proposes exact source sentence, anchor, destination and reason for each internal link." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="Explore Search Optimization" secondaryHref="/platform/search-optimization" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Proposed link · IL-302</p><p className="mt-4 rounded-xl border border-edge p-4 text-xs leading-6">For delegated user access, <span className="rounded bg-primary/15 px-1 text-primary">compare OAuth and API keys</span> before choosing an implementation.</p><div className="mt-3 text-[10px] text-fg-faint"><p>source · /docs/authentication</p><p className="mt-1">target · /guides/oauth-vs-api-keys</p><p className="mt-1 text-mint">destination 200 · no redirect · context fit high</p></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="What SEOForge detects" title="Orphans, weak paths and missed contextual relationships."/><PublicChecklist items={["Useful pages absent from relevant body copy","Important destinations reached only through navigation chrome","Anchors that are vague, repetitive or point through redirects","New articles without links from established related pages","Links whose destination no longer satisfies the surrounding sentence"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Finished change set</p><PublicChecklist items={["14 proposed links across nine source pages","Exact insertion sentence and descriptive anchor for each","Destination purpose and topic relationship","Rendered 200-status and canonical validation","Three suggestions excluded because the existing path was sufficient"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Link workflow" title="Model, propose, review and re-crawl."/><div className="mt-10"><PublicSteps steps={["Crawl rendered internal links and preferred URLs","Model page roles, topics, intents and conversion paths","Identify useful source-to-destination relationships","Generate exact natural-language insertion points","Validate destination, redirect, canonical and anchor diversity","Approve the content diff, deploy and re-crawl the graph"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Network} title="Graph evidence" body="Rendered links and preferred URLs establish the current state."/><PublicCard icon={Route} tone="mint" title="Reader path" body="The destination advances the task in the source sentence."/><PublicCard icon={Anchor} tone="amber" title="Natural anchor" body="Descriptive words fit the copy without forced exact-match repetition."/><PublicCard icon={Link2} tone="rose" title="Live check" body="Post-deploy crawl confirms status, canonical and rendered placement."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human approval" body="Review the exact source-page copy diff and destination. Bulk link insertion is never self-approved."/><PublicCard title="Capacity and measurement" body="Crawl depth and proposals consume paid capacity. Outcomes include graph coverage, discovery and page cohorts—not guaranteed ranking changes."/></div></PublicSection>
    <PublicFaq items={[["Does SEOForge add exact-match anchors everywhere?","No. Anchors should describe the destination naturally in the source context."],["Can it link through redirected URLs?","Proposals target the preferred final destination and validation flags redirect chains."],["Are navigation links included?","They are modeled, but contextual body links are evaluated separately for reader usefulness."],["What does a human approve?","Each source sentence, anchor, destination and production diff."],["Do more internal links guarantee rankings?","No. Useful linking supports discovery and navigation; search outcomes remain uncertain."]]}/>
    <PublicCta title="Build a link graph readers and crawlers can actually follow." body="Choose a paid plan to connect crawl evidence with precise, human-approved internal-link changes."/>
  </PublicShell>;
}

