import type { Metadata } from "next";
import { CalendarRange, LayoutTemplate, Palette, RefreshCw, Rocket, ShieldCheck } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Managed Website-Native Blog — SEOForge", description: "Build and operate a blog that matches your existing theme, uses human-approved publishing and feeds outcomes into a continuous content lifecycle.", alternates: { canonical: "/platform/managed-blog" } };

export default function ManagedBlogPage() {
  return <PublicShell>
    <PublicHero eyebrow="Managed blog" title="A blog that looks, publishes and improves like part of your website." description="SEOForge profiles your existing visual system and site architecture, prepares a website-native blog through GitHub or WordPress and operates the approved content lifecycle on your own domain." primary="Book a Managed Blog Demo" primaryHref="/demo" secondary="Review Publishing Plans" secondaryHref="/pricing" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Theme profile → blog route</p><div className="mt-4 grid grid-cols-5 gap-2">{["bg-primary","bg-mint","bg-amber","bg-panel","bg-fg-mute"].map(x=><span key={x} className={`h-8 rounded ${x}`}/>)}</div><div className="mt-4 rounded-xl border border-edge p-4"><p className="text-lg font-semibold">Your existing display type</p><p className="mt-2 text-xs leading-5 text-fg-mute">Matched content width, cards, spacing, navigation and responsive breakpoints.</p></div><p className="mt-3 text-[10px] text-mint">desktop + mobile screenshots passed</p></div>} />
    <PublicSection><PublicHeading eyebrow="Theme matching" title="The blog begins with a documented site profile."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><PublicCard icon={Palette} title="Visual DNA" body="Colors, typography, radii, shadows, spacing, imagery and responsive behavior."/><PublicCard icon={LayoutTemplate} tone="mint" title="Content system" body="Index, category, article, author, metadata, schema and related-content patterns."/><PublicCard icon={Rocket} tone="amber" title="Delivery path" body="Framework-native routes and protected pull requests or theme-native WordPress revisions."/><PublicCard icon={ShieldCheck} tone="rose" title="Approval" body="Blog infrastructure and every later article remain individually reviewable."/><PublicCard icon={CalendarRange} title="Content operation" body="Research, calendar, article, media and production capacity stay coordinated."/><PublicCard icon={RefreshCw} tone="mint" title="Lifecycle" body="Validate, observe, refresh, consolidate or roll back from measured evidence."/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Managed lifecycle" title="From site profile to a continuously maintained library."/><div className="mt-10"><PublicSteps steps={["Inspect the authorized framework, CMS, theme and analytics","Propose blog architecture, routes, content model and visual profile","Build the index and article templates with responsive previews","Require human approval before the blog infrastructure reaches production","Run the Content Growth pipeline for individually approved articles","Validate every deployment and annotate search and conversion baselines","Trigger refresh, consolidation or rollback from observed evidence"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Finished implementation" title="See the complete website-native package."/><PublicChecklist items={["/blog index, article route and category pattern","Theme-matched components and responsive content styles","Metadata, article and breadcrumb structured data","Optimized media rules, sitemap and feed integration","GitHub build or WordPress preview evidence","Desktop/mobile screenshots and rollback instructions"]}/></div><div className="marketing-card p-6"><p className="text-sm font-semibold">First article lifecycle</p><PublicChecklist items={["Approved opportunity and source-backed brief","Editorially reviewed article and original diagram","Website-native proposal with preview","Human publishing approval","Live crawl, schema, link and performance checks","Search, engagement and conversion observation"]}/></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human authority at every production step" body="Approving blog infrastructure does not authorize future articles. Each content or template change returns as its own proposal."/><PublicCard title="Paid managed capacity" body="Plan selection reflects site count, publishing system, article and media cadence, monitoring and implementation complexity. There is no free blog deployment."/></div></PublicSection>
    <PublicFaq items={[["Will the blog live on our domain?","The supported managed workflow is designed for website-native routes or an authorized WordPress installation."],["Can SEOForge match our current design?","It profiles the site and validates the proposed templates with responsive screenshots before approval."],["Does approving the blog auto-approve articles?","No. Every article and later production change receives separate review."],["Who owns the content and repository changes?","Work is prepared for the customer-authorized publishing destination and remains under customer production control."],["Are traffic or ranking results guaranteed?","No. SEOForge operates and measures the lifecycle without promising search-engine outcomes."]]}/>
    <PublicCta title="Build a blog that belongs to your website from day one." body="Book a paid managed-blog walkthrough to review your framework, theme, publishing path and operating capacity." primary="Book a Managed Blog Demo" href="/demo"/>
  </PublicShell>;
}
