import type { Metadata } from "next";
import { Bot, LockKeyhole, Workflow } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata: Metadata={title:"Autonomous SEO Platform With Human Approval — SEOForge",description:"Continuous content and optimization agents with locked production authority.",alternates:{canonical:"/autonomous-seo-platform"}};
export default function AutonomousSeoPlatformPage(){return <PublicShell>
 <PublicHero eyebrow="Autonomous SEO platform" title="Let the investigation run continuously. Keep production authority human." description="Four agents coordinate opportunity discovery, content creation, technical and content optimization, site-native implementation and measurement. Autonomy ends at the explicit approval gate." primary="Deploy My SEO Team" primaryHref="/pricing" secondary="Book a Product Walkthrough" secondaryHref="/demo" visual={<div className="marketing-card p-7"><Workflow className="text-primary"/><p className="mt-5 font-semibold">Two pipelines. One Supervisor. One locked gate.</p><PublicChecklist items={["Continuous scheduled work","Bounded tools and budgets","Evidence-backed proposals","No agent self-approval"]}/></div>}/>
 <PublicSection><PublicHeading eyebrow="Architecture" title="Specialists work independently without becoming a swarm."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={Workflow} title="Workflow Supervisor" body="Schedules work, enforces quotas, resolves conflicts, manages retries and preserves approval state."/><PublicCard icon={Bot} title="Specialist pipelines" body="Content Growth and Search Optimization pursue distinct queues and share current site evidence."/><PublicCard icon={LockKeyhole} title="Protected delivery" body="The Site Experience Engineer prepares changes but cannot approve, merge or deploy them."/></div></PublicSection>
 <PublicSection muted><PublicHeading eyebrow="Non-negotiable boundaries" title="Autonomous does not mean unaccountable."/><div className="mt-8 grid gap-4 md:grid-cols-2"><PublicCard title="The system can"><PublicChecklist items={["Monitor authorized providers","Investigate opportunities and failures","Prepare content, code, media and rollback context","Measure approved production outcomes"]}/></PublicCard><PublicCard title="The system cannot" tone="rose"><PublicChecklist negative items={["Approve its own proposal","Bypass branch or publishing protection","Retrieve or reveal provider credentials","Guarantee rankings, traffic or revenue"]}/></PublicCard></div></PublicSection>
 <PublicFaq items={[["Will agents create duplicate work?","The Supervisor checks active assignments, target URLs, keyword intent and proposal state before scheduling overlapping work."],["Can an API token deploy?","No. API, CLI and MCP access cannot approve, merge, deploy, retrieve credentials or bypass protection."],["Can I access the product free?","No. Product access begins after paid subscription and onboarding."]]}/><PublicCta title="Put autonomous capacity behind a human-controlled production gate." body="Compare paid plans or bring your workflow to a demo."/>
</PublicShell>}
