import type { Metadata } from "next";
import { Check, Minus } from "lucide-react";
import PricingExperience from "@/components/marketing/PricingExperience";
import { PublicCta, PublicFaq, PublicHeading, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title:"Pricing — SEOForge", description:"Paid SEOForge plans for continuous content growth, search optimization and protected production delivery. No free trial.", alternates:{canonical:"/pricing"} };
const rows = [["Content Growth pipeline",true,true,true],["Search Optimization pipeline",true,true,true],["Workflow Supervisor",true,true,true],["Site Experience Engineer",true,true,true],["Human production approval",true,true,true],["Competitor + backlink intelligence",false,true,true],["AI visibility probes",false,true,true],["API, webhooks and MCP",false,true,true],["Portfolio control room",false,false,true],["Same-workspace learning",false,false,true]] as const;
const faqs:Array<[string,string]>=[["What is a tracked query?","A keyword or phrase monitored for one engine, location, language and device. The same phrase in two locations counts as two tracked queries."],["Why is there no free trial?","SEOForge reserves provider, crawling, model, storage and agent capacity from activation and must validate real production permissions safely."],["Are the four agents included in every plan?","Yes. Plans change operational capacity, sites, queries, media and concurrency—not the integrity of the team."],["What happens when capacity is exhausted?","New work fails closed. The dashboard shows the limit and optional overages remain disabled until an authorized user enables them."],["Does an annual plan guarantee results?","No. Billing cadence changes price, not uncertainty. Search engines control rankings and SEOForge reports measured outcomes honestly."],["How does cancellation work?","Cancel renewal through the billing portal. Production access and data handling follow the effective subscription and retention policy shown during checkout."]];
export default function PricingPage(){return <PublicShell><section className="marketing-hero border-b border-edge"><div className="mx-auto max-w-5xl px-6 py-20 text-center sm:py-28"><p className="marketing-kicker justify-center"><span/>Paid operations · no free trial</p><h1 className="mt-6 text-balance text-4xl font-semibold sm:text-6xl">Choose the capacity your organic-growth operation needs.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-fg-mute">Every plan includes all four agents, both continuous pipelines and explicit production approval. Capacity—not vague AI access—scales with the plan.</p></div></section><PublicSection><PricingExperience/></PublicSection><PublicSection muted><PublicHeading eyebrow="Complete comparison" title="The operating model stays intact at every level."/><div className="mt-10 overflow-x-auto rounded-2xl border border-edge"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-panel"><tr><th className="p-4">Capability</th><th className="p-4">Starter</th><th className="p-4">Growth</th><th className="p-4">Agency</th></tr></thead><tbody>{rows.map(([name,...values])=><tr key={name} className="border-t border-edge"><td className="p-4 text-fg-mute">{name}</td>{values.map((v,i)=><td key={i} className="p-4">{v?<Check size={16} className="text-mint" aria-label="Included"/>:<Minus size={16} className="text-fg-faint" aria-label="Not included"/>}</td>)}</tr>)}</tbody></table></div></PublicSection><PublicFaq items={faqs}/><PublicCta title="Subscribe, complete readiness, then activate the team." body="Your site and publishing destination are connected only after paid subscription. Production authority remains with your authenticated reviewers."/></PublicShell>}
