import type { Metadata } from "next";
import { CalendarDays, Megaphone, SearchCheck } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"SEOForge vs Jasper — Fair Comparison (July 2026)",description:"Compare purpose-built SEO operations with general AI marketing content workflows.",alternates:{canonical:"/seoforge-vs-jasper"}};
export default function SeoForgeVsJasperPage(){return <PublicShell>
 <PublicHero eyebrow="Vendor-authored comparison · 20 July 2026" title="SEOForge vs Jasper: search operations or general marketing creation?" description="SEOForge focuses on search evidence, site-native proposals and measured production outcomes. Jasper is broadly positioned for AI-assisted marketing content. Scope—not a simplistic feature count—should drive the choice." primary="See SEOForge Work" primaryHref="/how-it-works" secondary="Read Full Comparison" secondaryHref="/compare/jasper" visual={<div className="marketing-card p-7"><CalendarDays className="text-primary"/><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-primary/10 p-4"><SearchCheck className="text-primary"/><p className="mt-3 text-xs">SEO operation</p></div><div className="rounded-xl bg-amber/10 p-4"><Megaphone className="text-amber"/><p className="mt-3 text-xs">Marketing creation</p></div></div></div>}/>
 <PublicSection><PublicHeading eyebrow="Fit" title="Use the specialist for the specialist job."/><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={SearchCheck} title="SEOForge may fit"><PublicChecklist items={["Search and site health must be monitored continuously","The output must become a validated website change","Deployment annotations and outcome windows are required"]}/></PublicCard><PublicCard icon={Megaphone} title="Jasper may fit better" tone="amber"><PublicChecklist items={["Your creation needs span marketing formats beyond SEO","Human marketers need a general-purpose content environment","SEO research, publishing and measurement already live elsewhere"]}/></PublicCard></div><p className="mt-8 text-sm leading-6 text-fg-mute">Competitor characterization reflects broad public positioning only. Verify Jasper’s current features, security, pricing and limitations directly. This page claims no access to Jasper customer data or private roadmap.</p></PublicSection>
 <PublicFaq items={[["Can SEOForge replace a general marketing platform?","Not necessarily. It is deliberately centered on content and search operations."],["Can Jasper help with SEO content?","It may support SEO-related workflows; verify the current product. The distinction here is the surrounding operating system."],["Does SEOForge offer free generation?","No. Product operation requires a paid plan."]]}/><PublicCta title="Choose SEOForge when search operations are the system you need." body="Compare paid plans or schedule a workflow demonstration."/>
</PublicShell>}
