import type { Metadata } from "next";
import { Boxes, CalendarDays, Workflow } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"SEOForge vs Search Atlas — Fair Comparison (July 2026)",description:"Compare a governed autonomous SEO operator with a broader SEO software suite.",alternates:{canonical:"/seoforge-vs-search-atlas"}};
export default function SeoForgeVsSearchAtlasPage(){return <PublicShell>
 <PublicHero eyebrow="Vendor-authored comparison · 20 July 2026" title="SEOForge vs Search Atlas: coordinated operator or broader suite?" description="SEOForge is architected around four agents, two pipelines and an explicit production gate. Search Atlas is positioned as a broader SEO platform. Your team’s desired level of direct tool operation is the key tradeoff." primary="Book a Demo" primaryHref="/demo" secondary="Read Full Comparison" secondaryHref="/compare/search-atlas" visual={<div className="marketing-card p-7"><CalendarDays className="text-primary"/><p className="mt-5 font-semibold">Evaluate the full run</p><p className="mt-3 text-sm leading-6 text-fg-mute">Evidence → priority → exact change → approval → production validation → measurement</p></div>}/>
 <PublicSection><PublicHeading eyebrow="Fit" title="Decide how the platform should participate in the work."/><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={Workflow} title="SEOForge may fit"><PublicChecklist items={["You want an agent system to coordinate recurring assignments","Conflicts, budgets, retries and approvals require one Supervisor","Developer surfaces must remain inspection and request interfaces only"]}/></PublicCard><PublicCard icon={Boxes} title="Search Atlas may fit better" tone="amber"><PublicChecklist items={["Specialists want broad SEO tooling in one suite","Your team prefers selecting and operating functions directly","Existing systems already govern implementation and measurement"]}/></PublicCard></div><p className="mt-8 text-sm leading-6 text-fg-mute">This is not an independent review. Confirm Search Atlas’s current features, automation, plans and contractual terms in its official materials. We make no claim about its private technology or customer outcomes.</p></PublicSection>
 <PublicFaq items={[["Does broader mean better?","No. Breadth and operational depth solve different problems. Demonstrate one representative workflow end to end."],["Do you claim Search Atlas lacks agents?","No. Product capabilities change; verify current functionality directly."],["Does SEOForge provide free access?","No. Choose a paid plan or book a demo."]]}/><PublicCta title="See whether governed autonomous operation matches your team." body="Bring your sites, providers and approval rules to a walkthrough." primary="Book a Demo" href="/demo" secondary="View Pricing" secondaryHref="/pricing"/>
</PublicShell>}
