import type { Metadata } from "next";
import { Eye, FileDiff, RotateCcw, ShieldCheck } from "lucide-react";
import ApprovalSandbox from "@/components/marketing/ApprovalSandbox";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Human Approval Workflow — SEOForge", description: "Review evidence, content and code diffs, previews, risk, validation and rollback before any SEOForge change reaches production.", alternates: { canonical: "/platform/human-approval" } };

export default function HumanApprovalPage() {
  return <PublicShell>
    <PublicHero eyebrow="Human approval" title="Autonomous work stops exactly where human authority begins." description="Agents research, draft and validate. They cannot self-approve, merge, deploy or publish. Every consequential change arrives as an individually reviewable proposal with evidence and rollback context." primary="Book an Approval Demo" primaryHref="/demo" secondary="Review Paid Plans" secondaryHref="/pricing" visual={<div className="marketing-card p-6"><ShieldCheck size={24} className="text-mint"/><p className="mt-5 text-lg font-semibold">Production boundary</p><PublicChecklist items={["Agent tools: prepare only","API, CLI and MCP: no approval endpoint","GitHub: protected merge remains human","WordPress: publication requires human action"]}/></div>} />
    <PublicSection><PublicHeading eyebrow="Interactive demonstration" title="Inspect the proposal and stage a decision." body="This sandbox changes only its local demonstration state. It cannot publish, call a provider or alter production."/><div className="mt-10"><ApprovalSandbox/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Approval packet" title="A yes or no backed by the complete decision surface."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Eye} title="Evidence and impact" body="Finding, sources, baseline, expected metric and uncertainty."/><PublicCard icon={FileDiff} tone="mint" title="Diff and preview" body="Exact content, code, media and rendered desktop/mobile result."/><PublicCard icon={ShieldCheck} tone="amber" title="Risk and validation" body="Affected routes, build, schema, links, smoke checks and residual risk."/><PublicCard icon={RotateCcw} tone="rose" title="Rollback" body="Revert commit or CMS revision plus post-revert verification."/></div></PublicSection>
    <PublicSection><PublicHeading eyebrow="Decision workflow" title="Every revision returns to a controlled state."/><div className="mt-10"><PublicSteps steps={["Agent submits one immutable proposal with evidence","Reviewer inspects files, diff, preview, checks and expected impact","Reviewer approves, rejects or requests a specific revision","Material revision creates a new validated proposal version","Approved GitHub merge or WordPress publication uses protected identity","Production checks attach results and can prepare rollback"]}/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="What approval does not mean" body="Approval does not guarantee rankings, validate unsupported claims or authorize future changes. It applies to one identified proposal version."/><PublicCard title="Paid access boundary" body="Approval operates inside subscribed workspaces after onboarding. The public sandbox is educational and offers no free product or production access."/></div></PublicSection>
    <PublicFaq items={[["Can an agent approve its own work?","No. Agent execution and authenticated human production approval are separate controls."],["Can an API token merge or publish?","No. Public developer surfaces cannot gain approval, merge, deploy or credential retrieval tools."],["What happens after I request changes?","The proposal returns to preparation and must pass relevant checks as a new version."],["Can I reject without publishing?","Yes. Rejection closes or returns the proposal and changes nothing in production."],["Is the interactive demo connected to a site?","No. It changes local demonstration state only and cannot publish anything."]]}/>
    <PublicCta title="Keep autonomous preparation fast and production authority human." body="Book a paid product walkthrough to inspect the approval boundary end to end." primary="Book a Product Walkthrough" href="/demo"/>
  </PublicShell>;
}
