import type { Metadata } from "next";
import { Building2, Gauge, UsersRound } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicProofNotice, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"SEO Automation for Agencies — SEOForge",description:"Operate isolated client sites with portfolio visibility, site-specific approval and governed capacity.",alternates:{canonical:"/seo-automation-for-agencies"}};
export default function SeoAutomationForAgenciesPage(){return <PublicShell>
 <PublicHero eyebrow="SEO automation for agencies" title="Scale client operations without blending client evidence or authority." description="SEOForge gives every site its own providers, context, budgets, queues and reviewers while portfolio views show capacity and risk. Agency teams keep the client relationship and final production authority." primary="Talk to Sales" primaryHref="/contact-sales" secondary="Book an Agency Demo" secondaryHref="/demo" visual={<div className="marketing-card p-7"><Building2 className="text-primary"/><p className="mt-5 font-semibold">Portfolio control room</p><div className="mt-4 space-y-2 text-xs"><p className="rounded-lg bg-panel-2 p-3">Client A · 3 proposals awaiting review</p><p className="rounded-lg bg-panel-2 p-3">Client B · provider reconnect needed</p><p className="rounded-lg bg-panel-2 p-3">Client C · within monthly capacity</p></div></div>}/>
 <PublicSection><PublicHeading eyebrow="Agency controls" title="Portfolio visibility with tenant-specific execution."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={Building2} title="Isolated sites" body="Connections, observations, artifacts and operational memory remain scoped to the authorized workspace and site."/><PublicCard icon={UsersRound} title="Client-specific approval" body="Assign reviewers and approval expectations per site; no portfolio role silently becomes universal publishing authority."/><PublicCard icon={Gauge} title="Governed capacity" body="See reserved and consumed provider, agent, keyword and publishing capacity before accepting more work."/></div></PublicSection>
 <PublicSection muted><div className="grid gap-8 lg:grid-cols-[1fr_.8fr]"><div><PublicHeading eyebrow="Before onboarding" title="Bring the operating contract, not only the URL list."/><PublicChecklist items={["Authorized providers and publishing destination per client","Brand, market and conversion rules per site","Reviewer ownership and escalation windows","Monthly capacity and provider-cost boundaries","Reporting definitions and attribution limitations","Offboarding, export and deletion expectations"]}/></div><PublicProofNotice/></div></PublicSection>
 <PublicFaq items={[["Can clients approve their own changes?","Reviewer roles can be designed around the agency-client operating model, while every production action remains explicit and authenticated."],["Does learning cross client sites?","Not by default. Client isolation and consent boundaries take priority over portfolio convenience."],["Is there a free agency tier?","No. Agency deployment is a paid sales-assisted path."]]}/><PublicCta title="Design an agency operating model that protects every client boundary." body="Talk to sales about sites, tracked markets, publishing volume, roles and onboarding." primary="Talk to Sales" href="/contact-sales" secondary="Book an Agency Demo" secondaryHref="/demo"/>
</PublicShell>}
