import type { Metadata } from "next";
import { CalendarCheck, Clock3, Link2, UserCheck } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Evidence-Backed Content Calendar — SEOForge", description: "Convert approved opportunities into a capacity-aware editorial calendar with dependencies, owners and measurement windows.", alternates: { canonical: "/platform/content-growth/content-calendar" } };

export default function ContentCalendarPage() {
  return <PublicShell>
    <PublicHero eyebrow="Content calendar" title="An editorial calendar should explain why this page ships next." description="SEOForge orders approved opportunities by customer value, topic dependencies, seasonal windows, production effort and available review capacity—not by an arbitrary promise to publish every Tuesday." primary="Choose a Content Plan" primaryHref="/pricing" secondary="See Keyword Research" secondaryHref="/platform/content-growth/keyword-research" visual={<div className="marketing-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold">August release board</p><span className="text-[10px] text-fg-faint">4 / 6 slots reserved</span></div><div className="mt-5 space-y-3">{[["06 AUG","OAuth vs API keys","brief approved"],["13 AUG","Token rotation","source review"],["22 AUG","Service accounts","depends on docs PR"]].map(([d,t,s])=><div key={t} className="grid grid-cols-[64px_1fr] gap-3 rounded-xl border border-edge p-3"><span className="display text-[10px] text-primary">{d}</span><span className="text-xs"><b>{t}</b><small className="mt-1 block text-fg-faint">{s}</small></span></div>)}</div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><PublicHeading eyebrow="From backlog to commitment" title="Capacity, dependencies and reviewers stay visible." body="The calendar is the operating agreement between the research backlog and the people who must validate production."/></div><div className="grid gap-4 sm:grid-cols-2"><PublicCard icon={CalendarCheck} title="Priority window" body="Why the work belongs in this publishing period."/><PublicCard icon={Link2} tone="mint" title="Dependencies" body="Required source, product, documentation or internal-link work."/><PublicCard icon={UserCheck} tone="amber" title="Decision owner" body="Named brief, editorial and production reviewers."/><PublicCard icon={Clock3} tone="rose" title="Observation window" body="When the deployed page receives its first meaningful review."/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Scheduling workflow" title="The Supervisor reserves real operational capacity."/><div className="mt-10"><PublicSteps steps={["Collect approved opportunities and active refresh obligations","Estimate research, writing, media and implementation effort","Order topic dependencies and business-critical windows","Reserve plan capacity and named human review time","Lock the brief before drafting; expose any blocked dependency","Rebalance when evidence, product launches or production state changes"]} accent="amber"/></div></PublicSection>
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Example input</p><p className="mt-4 text-sm leading-6 text-fg-mute">Nine approved opportunities, two urgent documentation refreshes, one product launch on August 20, two editorial reviewers and Growth-plan capacity.</p></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Finished calendar output</p><PublicChecklist items={["Four scheduled articles with stage and owner","Two opportunities deferred with capacity reason","One topic blocked until product documentation ships","Dedicated post-deploy observation dates","Visible content and media capacity reservation"]}/></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><div><PublicHeading eyebrow="Human control" title="Changing the date never changes publishing authority."/><p className="mt-5 text-sm leading-6 text-fg-mute">Reviewers can reorder, pause or reject planned work. Each eventual article still requires separate editorial and production approval.</p></div><div className="marketing-card p-6"><p className="text-sm font-semibold">Capacity framing</p><p className="mt-3 text-sm leading-6 text-fg-mute">Starter supports a focused cadence; Growth adds articles, media and concurrent work; Agency adds isolated client calendars and portfolio oversight. Current allowances live on pricing.</p></div></div></PublicSection>
    <PublicFaq items={[["Does SEOForge auto-publish on calendar dates?","No. Dates schedule work; only explicit approval authorizes a production proposal."],["What happens when capacity is full?","Lower-priority work is deferred with the reason visible. The system does not silently overrun plan limits."],["Can launch dates change the plan?","Yes. A human can reprioritize and the Supervisor recalculates dependencies, capacity and review windows."],["Are refreshes included with new content?","Both pipelines compete for governed site capacity, so urgent existing-content work remains visible beside new articles."],["Does a fixed cadence improve rankings?","Not by itself. The calendar coordinates useful work; search outcomes depend on quality, demand, authority and many external factors."]]}/>
    <PublicCta title="Replace the publishing treadmill with an accountable calendar." body="Choose a paid plan and reserve content, media and review capacity against the opportunities that matter most."/>
  </PublicShell>;
}
