import type { Metadata } from "next";
import { Bot, ChartNoAxesCombined, MessageSquareQuote, ScanSearch } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "GEO and AI Visibility — SEOForge", description: "Track controlled answer-engine probes, citations and answer-ready content while keeping synthetic observations separate from real traffic.", alternates: { canonical: "/platform/geo" } };

export default function GeoPage() {
  return <PublicShell>
    <PublicHero eyebrow="GEO and AI visibility" title="Measure answer-engine visibility without calling synthetic prompts customer traffic." description="SEOForge runs repeatable, labeled probes across supported answer surfaces, records citations and answer context, and separately reports real customer-owned search and analytics evidence." primary="Choose an AI Visibility Plan" primaryHref="/pricing" secondary="See the Methodology" secondaryHref="/tools/ai-visibility-methodology" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">AI visibility observation</p><div className="mt-4 rounded-xl border border-primary/25 bg-primary/8 p-4 text-xs"><p>Probe: “How should a SaaS rotate API credentials?”</p><p className="mt-3 text-mint">Brand mentioned · source cited</p><p className="mt-2 text-fg-faint">Synthetic prompt · US English · 20 Jul · repeat 3/5</p></div><div className="mt-3 rounded-xl border border-edge p-4 text-xs"><p>GA4 organic sessions</p><p className="mt-2 text-fg-faint">Separate customer-owned traffic evidence · not inferred from probe</p></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Two evidence lanes" title="Probes describe answer behavior. Analytics describes visitors."/><PublicChecklist items={["Probe lane: prompt, engine, locale, timestamp, answer, citations and repeat rate","Traffic lane: authorized Search Console and GA4 observations","No conversion, visit or revenue is inferred from a synthetic answer","No single prompt is presented as population-level market share"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Finished GEO recommendation</p><p className="mt-5 text-sm"><b>Finding:</b> the API-rotation guide is cited in 1 of 5 controlled repeats; answers omit the brand’s revocation workflow.</p><p className="mt-3 text-sm"><b>Change:</b> add a source-backed, answer-first revocation sequence, clarify the organization entity and validate HowTo markup against visible content.</p><p className="mt-3 text-sm"><b>Measure:</b> rerun the same probe set and separately observe real landing-page search cohorts.</p></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="GEO workflow" title="Observe retrieval, improve clarity and repeat the same test."/><div className="mt-10"><PublicSteps steps={["Define an approved prompt set, engine, locale and repeat policy","Capture answer text, brand mention, cited URLs and timestamp","Audit entity clarity, passage answerability and source support","Prioritize gaps by relevance, repeatability, business fit and risk","Prepare exact content or structured-data change for approval","Deploy, rerun probes and separately observe real traffic evidence"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Bot} title="Controlled probes" body="Labeled synthetic questions make answer behavior repeatable and auditable."/><PublicCard icon={MessageSquareQuote} tone="mint" title="Citation evidence" body="Mention, linked source and surrounding answer remain attached."/><PublicCard icon={ScanSearch} tone="amber" title="Page change" body="Improve factual clarity, entity context and answer-ready passages without fabrication."/><PublicCard icon={ChartNoAxesCombined} tone="rose" title="Real traffic" body="Search and analytics data stay in a separate customer-owned evidence lane."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Review the prompt methodology, cited answer evidence and exact content or schema diff. No agent may publish the change."/><PublicCard title="Capacity and claims" body="Plans define probe sets, engines, cadence and execution. SEOForge does not guarantee inclusion, citation, traffic or revenue from answer engines."/></div></PublicSection>
    <PublicFaq items={[["Are AI visibility probes real traffic?","No. They are synthetic observations of answer behavior and are labeled separately from analytics."],["Can one prompt prove visibility?","No. Repeat sets, engine, locale and time context are required, and results remain samples."],["What does SEOForge optimize?","Clear entities, well-supported answer passages, source quality, structure and useful page coverage."],["Can GEO guarantee a citation?","No. Answer engines control generation and sourcing."],["What does a human approve?","The exact content or structured-data change and its measurement plan."]]}/>
    <PublicCta title="Build AI visibility on evidence—not synthetic-traffic claims." body="Choose a paid plan with the probe and optimization capacity your brand requires."/>
  </PublicShell>;
}

