import type { Metadata } from "next";
import { Image, NotebookPen, PanelsTopLeft } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"AI Blog Generation Platform for Real Websites — SEOForge",description:"Generate source-backed, brand-aligned articles and prepare them for governed website publishing.",alternates:{canonical:"/ai-blog-generation-platform"}};
export default function AiBlogGenerationPlatformPage(){return <PublicShell>
 <PublicHero eyebrow="AI blog generation platform" title="Generate the article, the media and the production-ready website change." description="SEOForge starts with a qualified opportunity and ends with an approval-ready GitHub or WordPress proposal—not a detached document. Editorial checks, previews and measurement stay attached." primary="Choose a Content Plan" primaryHref="/pricing" secondary="See How It Works" secondaryHref="/how-it-works" visual={<div className="marketing-card overflow-hidden"><div className="border-b border-edge p-5 text-xs text-fg-faint">Illustrative article package</div><div className="p-7"><PanelsTopLeft className="text-primary"/><p className="mt-5 text-lg font-semibold">Topic cluster / implementation guide</p><div className="mt-4 h-2 w-full rounded bg-edge"/><div className="mt-2 h-2 w-4/5 rounded bg-edge"/><div className="mt-5 rounded-xl bg-amber/10 p-4 text-xs text-amber">6 sources · 4 internal links · media brief ready</div></div></div>}/>
 <PublicSection><PublicHeading eyebrow="Finished outcome" title="A complete editorial package built for your site."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={NotebookPen} title="Evidence-backed draft" body="Intent, sources, entities, questions, brand rules and conversion purpose shape the brief before drafting."/><PublicCard icon={Image} title="Useful original media" body="Diagrams and article visuals include purpose, placement and accessibility metadata—not decorative filler."/><PublicCard icon={PanelsTopLeft} title="Website-native preview" body="Routes, components, metadata, links and build behavior are validated against the actual destination."/></div></PublicSection>
 <PublicSection muted><div className="grid gap-8 lg:grid-cols-2"><div><PublicHeading eyebrow="Editorial gate" title="Review what matters before production."/><PublicChecklist items={["Claims have sources or are clearly qualified","The article satisfies the searcher’s task without padding","Internal links are relevant and naturally anchored","Media adds information and has alt text","Conversion paths match the page intent","The final diff is visible before approval"]}/></div><PublicCard title="Important limitation" body="SEOForge cannot prove future rankings, originality from a single score, or factual accuracy without appropriate sources. Human editorial judgment remains necessary for sensitive, expert or brand-critical claims." tone="amber"/></div></PublicSection>
 <PublicFaq items={[["Can it match our blog design?","The Site Experience Engineer inspects the authorized repository or WordPress structure before proposing implementation, but your team reviews the result."],["Does it publish on its own?","No. Production requires explicit authenticated human approval."],["Is there a free generator?","No. Public education is free to read; product operation is paid."]]}/><PublicCta title="Build a blog pipeline connected to the website it serves." body="Select paid publishing capacity or book a walkthrough for your stack."/>
</PublicShell>}
