import type { Metadata } from "next";
import { CalendarCheck, FileText, Image, Search } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Content Growth Agent — SEOForge", description: "Meet the agent that turns qualified opportunities into briefs, sourced articles, original media and governed publishing proposals.", alternates: { canonical: "/agents/content-growth" } };

export default function ContentGrowthAgentPage() {
  return <PublicShell>
    <PublicHero eyebrow="Agent 02 · Content Growth" title="The specialist that turns a search opportunity into a complete article package." description="The Content Growth Agent owns the journey from defensible opportunity to approved brief, source-backed draft, useful media and website-native publishing proposal." primary="Deploy Content Growth" primaryHref="/pricing" secondary="Explore the Pipeline" secondaryHref="/platform/content-growth" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Artifact bundle · CG-441</p><div className="mt-4 grid grid-cols-2 gap-3 text-[10px]"><span className="rounded border border-edge p-4">opportunity<br/><b className="text-mint">approved</b></span><span className="rounded border border-edge p-4">brief<br/><b className="text-mint">locked</b></span><span className="rounded border border-edge p-4">article<br/><b className="text-amber">editorial</b></span><span className="rounded border border-edge p-4">media<br/><b className="text-primary">2 assets</b></span></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Assignment input" title="Audience, evidence and boundaries arrive before the draft."/><PublicChecklist items={["Product area, buyer stage, market and approved search opportunity","Existing content map and active-topic ownership","Source policy, brand voice and prohibited claims","Article role, conversion purpose and media allowance","Repository or CMS constraints and review owners"]}/></div><div><PublicHeading eyebrow="Finished output" title="A publishable package—not loose prose."/><PublicChecklist items={["Opportunity report and evidence-backed content brief","Complete article with claim-level source support","Original hero, explanatory diagram and accessibility metadata","Internal links, metadata and conversion path","Validated GitHub or WordPress proposal awaiting human approval"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Agent workflow" title="Research and creation stay autonomous; production does not."/><div className="mt-10"><PublicSteps steps={["Validate opportunity against site coverage and active assignments","Build intent, source, entity and question maps","Lock the brief and article’s customer task","Draft, source and edit the complete article","Create purpose-built media and production metadata","Hand off to Site Experience and human approval"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Search} title="Opportunity" body="A distinct customer need with evidence and business fit."/><PublicCard icon={CalendarCheck} tone="amber" title="Plan" body="Dependencies, capacity and reviewers remain visible."/><PublicCard icon={FileText} tone="mint" title="Article" body="Source-backed, brand-aligned and editorially reviewed."/><PublicCard icon={Image} tone="rose" title="Media" body="Useful, accessible assets built for the article’s purpose."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Editors review claims, sources, voice, media and preview. Production approval applies to the exact proposal only."/><PublicCard title="Paid capacity" body="Plans bound opportunities, articles, media and agent execution. The agent never claims every article will rank or convert."/></div></PublicSection>
    <PublicFaq items={[["Can the agent choose topics by volume alone?","No. Intent, business fit, current coverage, evidence and differentiation determine priority."],["Can it copy competitor content?","No. Market observations inform an original page built for your audience."],["Does it publish completed drafts?","No. Editorial and production approvals remain human."],["What integrations does it use?","Authorized research providers, site content, GitHub or WordPress, Search Console and GA4 where connected."],["Are article results guaranteed?","No. Outcomes are measured after deployment without ranking or revenue promises."]]}/>
    <PublicCta title="Deploy a content specialist connected to your real website." body="Choose a paid plan with the research, article and media capacity your operating cadence needs."/>
  </PublicShell>;
}

