import type { Metadata } from "next";
import { Braces, Gauge, Link2Off, RotateCcw, SearchCheck, ServerCog } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Production Validation — SEOForge", description: "Verify deployments, smoke-test affected pages, check crawl, schema, links and performance, then monitor indexing and regressions.", alternates: { canonical: "/platform/production-validation" } };

export default function ProductionValidationPage() {
  return <PublicShell>
    <PublicHero eyebrow="Production validation" title="Publishing is the midpoint, not the finish line." description="SEOForge verifies the deployed version, tests the affected experience, checks crawl and structured data, compares performance and starts indexing and ranking observation. A regression becomes a rollback proposal—not a hidden failure." primary="Choose a Protected Plan" primaryHref="/pricing" secondary="See Human Approval" secondaryHref="/platform/human-approval" visual={<div className="marketing-card p-5"><div className="flex justify-between"><p className="text-xs font-semibold">Deploy 82ba1 · live checks</p><span className="text-[10px] text-mint">7/8 passed</span></div><div className="mt-5 grid grid-cols-2 gap-2 text-[10px]">{[["version","pass"],["HTTP + render","pass"],["canonical","pass"],["schema","pass"],["links","pass"],["mobile smoke","pass"],["LCP compare","warn"],["index watch","active"]].map(([x,s])=><span key={x} className="rounded border border-edge p-3">{x}<b className={`float-right ${s==='warn'?'text-amber':'text-mint'}`}>{s}</b></span>)}</div></div>} />
    <PublicSection><PublicHeading eyebrow="Post-deploy checks" title="Prove the production artifact—not just the preview."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><PublicCard icon={ServerCog} title="Deployment verification" body="Confirm the expected commit or revision, final URL, HTTP state and rendered content."/><PublicCard icon={SearchCheck} tone="mint" title="Crawl and indexing" body="Check robots, canonical, sitemap presence and ongoing search-engine observations without promising indexing."/><PublicCard icon={Braces} tone="amber" title="Schema" body="Validate rendered JSON-LD against visible content and required properties."/><PublicCard icon={Link2Off} tone="rose" title="Broken links" body="Re-crawl affected routes and the new page’s outgoing destinations."/><PublicCard icon={Gauge} title="Performance comparison" body="Compare like-for-like lab runs and available field evidence by device."/><PublicCard icon={RotateCcw} tone="rose" title="Regression and rollback" body="Threshold breaches preserve evidence and prepare a human-reviewed revert."/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Validation workflow" title="A deployment receives an immediate check and a longer observation window."/><div className="mt-10"><PublicSteps steps={["Verify expected commit, CMS revision and affected URL set","Run HTTP, render, console and critical-interaction smoke tests","Check canonical, robots, schema, sitemap and outgoing links","Compare performance with the approved pre-deploy baseline","Annotate indexing and ranking monitors with the deployment","Escalate regression and prepare rollback for human approval"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Example regression" title="A valid page can still be a bad deployment."/><PublicChecklist items={["Content and schema passed on /guides/oauth","Mobile LCP regressed from 2.1s to 4.0s in matched lab runs","Cause isolated to an unoptimized 2.8 MB hero asset","Proposal replaces it with a 126 KB responsive WebP","Rollback remains available if the corrected deploy fails smoke checks"]}/></div><div className="marketing-card p-6"><p className="text-sm font-semibold">Measurement continues after technical pass</p><p className="mt-4 text-sm leading-6 text-fg-mute">Indexing observation, Search Console cohorts, rank annotations and conversion metrics use their own windows. “Passed validation” means production matches the approved artifact and safety checks—not that rankings improved.</p></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human rollback authority" body="SEOForge can recommend and prepare a rollback. A protected production revert still requires the authorized workflow."/><PublicCard title="Plan capacity" body="Check cadence, crawl scope, retention and observation volume use paid capacity. Critical checks fail closed when required evidence is unavailable."/></div></PublicSection>
    <PublicFaq items={[["What is checked immediately after deployment?","Version, URL, status, render, console, canonical, robots, schema, links, responsive smoke and baseline performance."],["Does passing validation mean Google indexed the page?","No. Indexing is monitored separately and cannot be guaranteed."],["What happens on a performance regression?","Evidence is attached, the cause is investigated and a correction or rollback proposal enters human review."],["Can SEOForge roll back automatically?","No. It prepares rollback context; protected production action remains authorized by a human."],["How long are rankings observed?","The window is chosen for the page and query cohort and remains visible with known confounders."]]}/>
    <PublicCta title="Protect every approved change after it reaches the live site." body="Choose a paid plan with production checks, ongoing observation and rollback-ready delivery."/>
  </PublicShell>;
}

