import type { Metadata } from "next";
import { Blocks, Braces, Camera, GitPullRequest, Palette, RotateCcw } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Site Experience Engineer — SEOForge", description: "Turn approved SEO work into framework-native or WordPress-native diffs with builds, screenshots and rollback instructions.", alternates: { canonical: "/platform/site-experience-engineer" } };

export default function SiteExperienceEngineerPage() {
  return <PublicShell>
    <PublicHero eyebrow="Site Experience Engineer" title="Production work that belongs inside your website." description="Before preparing a change, SEOForge identifies the framework or CMS, repository conventions, theme, design tokens, content model, build commands and protected delivery path." primary="Choose a Publishing Plan" primaryHref="/pricing" secondary="Book a Demo" secondaryHref="/demo" visual={<div className="marketing-card p-5 font-mono text-[10px]"><p className="text-fg-faint">SITE PROFILE · github/app-router</p><p className="mt-4 text-mint">framework: Next.js 16 · App Router</p><p className="mt-2 text-mint">theme: dark · tokens in globals.css</p><p className="mt-2 text-fg-mute">content: MDX · /src/content/guides</p><p className="mt-2 text-fg-mute">build: npm run build</p><p className="mt-4 rounded border border-primary/25 bg-primary/8 p-3 text-primary">branch: seoforge/refresh-oauth</p></div>} />
    <PublicSection><PublicHeading eyebrow="Repository understanding" title="The site profile is a prerequisite, not an afterthought."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><PublicCard icon={Blocks} title="Framework detection" body="Routes, rendering mode, content source, image behavior and metadata conventions."/><PublicCard icon={Palette} tone="mint" title="Theme matching" body="Colors, type, spacing, components, breakpoints and existing blog patterns."/><PublicCard icon={Braces} tone="amber" title="Exact diff" body="Repository-native content, code, schema, links and configuration changes."/><PublicCard icon={GitPullRequest} title="Protected delivery" body="A branch and pull request or governed WordPress proposal—never a production shortcut."/><PublicCard icon={Camera} tone="rose" title="Build and screenshots" body="Typecheck, build and route checks plus desktop and mobile preview captures."/><PublicCard icon={RotateCcw} tone="mint" title="Rollback" body="Revert commit or CMS revision with affected paths and post-revert checks."/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Implementation workflow" title="Profile, implement, prove and hand over."/><div className="mt-10"><PublicSteps steps={["Inspect authorized framework, theme and publishing structure","Map the approved artifact to site-native routes and components","Create a bounded branch or WordPress revision proposal","Apply content, code, media, metadata and link diffs","Run typecheck, build, lint, schema and broken-link validation","Capture responsive screenshots and attach rollback instructions","Route the complete proposal to a human reviewer"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Example production packet" title="A finished route, checked against the real theme."/><PublicChecklist items={["Input: approved OAuth comparison article and decision diagram","Files: page.mdx, oauth-decision.webp, related-links.ts and sitemap.ts","Theme: existing card radius, muted palette and responsive prose width","Checks: build passed; links 200; JSON-LD valid; no console error","Screenshots: 1440px desktop and 390px mobile","Rollback: revert commit 82ba1 and re-run affected route smoke checks"]}/></div><div className="marketing-card p-6 font-mono text-[11px]"><p className="text-fg-faint">PULL REQUEST #184</p><p className="mt-4 text-mint">+ src/content/guides/oauth-vs-api-keys.mdx</p><p className="mt-2 text-mint">+ public/media/oauth-decision.webp</p><p className="mt-2 text-amber">~ src/app/sitemap.ts</p><p className="mt-5 rounded border border-edge p-3 text-fg-mute">type ✓ build ✓ links ✓ schema ✓ screenshots 2</p></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human production review" body="Review the exact files or CMS fields, visual preview, checks, risk and rollback. Agents cannot merge a branch or publish WordPress."/><PublicCard title="Paid implementation capacity" body="Plans define sites, concurrent work and execution capacity. Unsupported frameworks or failing builds stay blocked instead of being forced through."/></div></PublicSection>
    <PublicFaq items={[["How does SEOForge match our design?","It profiles approved design tokens and existing route patterns, then validates the implementation with responsive screenshots."],["Can it work with WordPress?","Yes. It maps the theme, editor fields, media, taxonomies and revision process before preparing a proposal."],["What if the build fails?","The proposal remains blocked with logs and the failing check; it cannot reach approval as production-ready."],["Can the agent merge its pull request?","No. Merge, deploy and WordPress publication require the protected human workflow."],["Is rollback automatic?","SEOForge prepares rollback instructions or a proposal; consequential rollback still requires authorization."]]}/>
    <PublicCta title="Connect approved SEO work to a website-native delivery layer." body="Choose a paid plan and onboard one authorized repository or WordPress destination."/>
  </PublicShell>;
}

