import type { Metadata } from "next";
import { Activity, Link2, ScanSearch, Wrench } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Search Optimization Agent — SEOForge", description: "Meet the agent that monitors rankings, technical health, decay, links, competitors and backlinks, then prepares precise improvements.", alternates: { canonical: "/agents/search-optimization" } };

export default function SearchOptimizationAgentPage() {
  return <PublicShell>
    <PublicHero eyebrow="Agent 03 · Search Optimization" title="The specialist that never assumes a published page is finished." description="The Search Optimization Agent continuously tests search, analytics, crawl and market evidence, diagnoses material changes and prepares the smallest defensible production response." primary="Deploy Search Optimization" primaryHref="/pricing" secondary="Explore the Pipeline" secondaryHref="/platform/search-optimization" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Investigation SO-731</p><div className="mt-4 space-y-2 text-[11px]"><p className="rounded border border-edge p-3">signal · non-brand clicks −31%</p><p className="rounded border border-edge p-3">technical state · healthy</p><p className="rounded border border-edge p-3">intent shift · comparison + implementation</p><p className="rounded border border-mint/25 bg-mint/8 p-3 text-mint">decision · bounded refresh</p></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Investigation input" title="Multiple evidence lanes prevent one-metric decisions."/><PublicChecklist items={["Rank and SERP cohorts by market and device","Search Console query and landing-page observations","GA4 engagement and qualified conversion evidence","Rendered crawl, schema, links and performance state","Competitor, backlink and labeled AI-probe context"]}/></div><div><PublicHeading eyebrow="Finished output" title="An exact change with a baseline and stop condition."/><PublicChecklist items={["Evidence-backed finding or explicit no-action decision","Priority with impact, confidence, effort and risk","Content, link, metadata, code or redirect proposal","Validation, preview, human decision and rollback context","Post-deploy metric, cohort and observation window"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Agent workflow" title="Monitor, diagnose, change and measure."/><div className="mt-10"><PublicSteps steps={["Detect a material scheduled or event-driven signal","Confirm it across relevant evidence and time windows","Rule out tracking, seasonality and production confounders","Prioritize against active site work and capacity","Prepare and validate the smallest useful change","Require approval and measure the original cohort"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Activity} title="Rank evidence" body="Cohorts and annotations replace isolated position alerts."/><PublicCard icon={Wrench} tone="rose" title="Technical state" body="Rendered production checks locate shared root causes."/><PublicCard icon={ScanSearch} tone="amber" title="Content diagnosis" body="Decay, intent and overlap determine the editorial action."/><PublicCard icon={Link2} tone="mint" title="Market graph" body="Internal links, competitors and backlinks provide context with uncertainty."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Review the evidence, exact diff, expected metric, validation and rollback before any production action."/><PublicCard title="Plan boundary" body="Tracked queries, sites, monitoring and execution are capacity limited. The agent cannot promise recovery or rank positions."/></div></PublicSection>
    <PublicFaq items={[["Does every alert become a change?","No. Weak, noisy or confounded evidence can end in observation or no action."],["Can the agent fix technical issues?","It prepares framework-native or CMS-native changes for validation and human approval."],["How does it measure impact?","With a declared baseline, deployment annotation, cohort and observation window."],["Can it approve its proposal?","No. Agent execution and production approval are separate."],["Does it guarantee ranking recovery?","No. Search engines control distribution; SEOForge measures controllable improvements."]]}/>
    <PublicCta title="Deploy continuous optimization with an explicit evidence trail." body="Choose a paid plan with the monitoring and execution capacity your existing library needs."/>
  </PublicShell>;
}

