import type { Metadata } from "next";
import { Boxes, FileQuestion, Map, Split } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Content Gap Intelligence — SEOForge", description: "Find missing customer questions and topical coverage without copying competitors or creating duplicate pages.", alternates: { canonical: "/platform/content-growth/content-gaps" } };

export default function ContentGapsPage() {
  return <PublicShell>
    <PublicHero eyebrow="Content-gap intelligence" title="Find the missing page between your expertise and your customer’s next question." description="SEOForge compares the customer journey, your current library, search results and competitor coverage to locate omissions worth filling—then defines the distinct job the new page must do." primary="Choose a Content Plan" primaryHref="/pricing" secondary="Explore Content Growth" secondaryHref="/platform/content-growth" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Authentication cluster</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl border border-mint/25 bg-mint/8 p-4"><p className="text-mint">Covered</p><p className="mt-3">API authentication guide</p><p className="mt-2">Token rotation docs</p></div><div className="rounded-xl border border-amber/25 bg-amber/8 p-4"><p className="text-amber">Missing journey step</p><p className="mt-3 font-semibold">OAuth vs API key decision guide</p></div></div><p className="mt-3 rounded-lg border border-edge p-3 text-[11px] text-fg-mute">Recommended role: mid-funnel comparison · confidence 0.87</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="The actual problem" title="Competitor keywords do not automatically belong on your site." body="A useful gap is an unanswered audience need that advances your topical system. It is not every phrase another domain happens to rank for."/><PublicChecklist negative items={["Copying a competitor’s navigation as a content plan","Splitting one intent across multiple thin articles","Calling low-volume customer questions unimportant"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Example gap report</p><p className="mt-5 text-sm"><b>Input:</b> 42 existing authentication URLs, buyer journey, three comparable domains and current SERPs.</p><p className="mt-4 text-sm"><b>Output:</b> one net-new comparison guide, two expansions to existing docs and six competitor topics excluded as off-product.</p><PublicChecklist items={["New page: OAuth vs API keys","Expand: service-account setup","Expand: token rotation examples","Exclude: consumer password-manager topics"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Gap workflow" title="Map the journey before opening a draft."/><div className="mt-10"><PublicSteps steps={["Inventory published, scheduled and in-progress content","Model topics, entities, intents and customer-journey stages","Observe search results and relevant competitor coverage","Separate missing pages from weak sections on existing pages","Score distinct value, business fit, confidence and effort","Approve a new brief, an expansion or no action"]}/></div></PublicSection>
    <PublicSection><PublicHeading eyebrow="Finished decisions" title="Every gap ends in a specific content action."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={FileQuestion} title="Create" body="A distinct intent needs a useful page of its own."/><PublicCard icon={Boxes} tone="mint" title="Expand" body="The preferred existing page can answer the missing question."/><PublicCard icon={Split} tone="amber" title="Consolidate" body="Overlapping pages should become one clearer destination."/><PublicCard icon={Map} tone="rose" title="Exclude" body="The topic lacks product fit, evidence or a unique reason to exist."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-5 lg:grid-cols-3"><PublicCard title="Human review" body="Approve the content action, scope and page ownership. A gap decision cannot self-authorize publication."/><PublicCard title="Plan capacity" body="Site inventory, competitor observations and planned artifacts consume paid operational capacity shown in pricing and usage."/><PublicCard title="Measurement" body="Accepted gaps inherit a baseline and are later observed for query coverage, qualified engagement and conversion contribution."/></div></PublicSection>
    <PublicFaq items={[["Is this a competitor keyword export?","No. Competitors supply context, while your audience, product, existing coverage and distinct value decide the action."],["How do you avoid duplicate articles?","Published URLs, scheduled work and active assignments are mapped before a new brief is allowed."],["Can the result recommend no new page?","Yes. Expanding an existing page or deliberately excluding a topic is often the better decision."],["What does the reviewer approve?","The gap classification, intended page owner, scope, exclusions and next artifact."],["Does closing a gap guarantee traffic?","No. It improves coverage deliberately; actual visibility and business outcomes are measured after publication."]]}/>
    <PublicCta title="Build coverage your customers actually need." body="Choose a paid content plan to map gaps across your site and route only approved opportunities into production."/>
  </PublicShell>;
}

