import type { Metadata } from "next";
import { Activity, GitPullRequest, Layers3, ShieldCheck, Sparkles } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicProofNotice, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Autonomous SEO Operations Platform — SEOForge", description: "Coordinate content creation, continuous optimization, website-native delivery and human approval in one paid SEO operations platform.", alternates: { canonical: "/platform" } };

export default function PlatformPage() {
  return <PublicShell>
    <PublicHero eyebrow="SEO operations platform" title="Four specialists. Two continuous pipelines. One accountable system." description="SEOForge researches new demand and protects the pages you already own, then turns approved ideas into validated GitHub or WordPress changes. Every live change remains under human authority." primary="Choose Your Plan" primaryHref="/pricing" secondary="See How SEOForge Works" secondaryHref="/how-it-works" visual={<div className="marketing-card p-5"><div className="flex items-center justify-between border-b border-edge pb-4"><span className="text-xs font-semibold">Supervisor control room</span><span className="rounded-full bg-mint/10 px-3 py-1 text-[10px] text-mint">2 pipelines healthy</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-primary/25 bg-primary/8 p-4"><Sparkles size={17} className="text-primary"/><p className="mt-5 text-sm font-semibold">Content Growth</p><p className="mt-2 text-xs text-fg-faint">Opportunity → brief → article → media</p></div><div className="rounded-xl border border-amber/25 bg-amber/8 p-4"><Activity size={17} className="text-amber"/><p className="mt-5 text-sm font-semibold">Search Optimization</p><p className="mt-2 text-xs text-fg-faint">Monitor → diagnose → improve → measure</p></div></div><div className="mt-3 rounded-xl border border-edge bg-[#080a0f] p-4 font-mono text-[11px] text-fg-mute"><p>priority: refresh /docs/api-auth</p><p className="mt-2 text-amber">state: awaiting human approval</p><p className="mt-2 text-mint">budget: 71% remaining</p></div></div>} />
    <PublicSection><PublicHeading eyebrow="Complete operating loop" title="The work does not stop at a recommendation." body="Every assignment moves from observed evidence to a production artifact, an explicit decision and a measured conclusion."/><div className="mt-12"><PublicSteps steps={["Connect an authorized site, publishing destination and analytics property","Set brand rules, markets, budgets and production boundaries","Run Content Growth and Search Optimization on independent queues","Review the exact content or code proposal with evidence","Publish only after approval and validate the live site","Keep, iterate or prepare rollback from measured evidence"]}/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Four-agent architecture" title="Specialists own the handoffs—not just the prompts."/><div className="mt-12 grid gap-5 md:grid-cols-2"><PublicCard icon={Layers3} title="Workflow Supervisor" body="Schedules work, reserves budgets, checks heartbeats, resolves conflicts and prevents duplicates."/><PublicCard icon={Sparkles} tone="mint" title="Content Growth Agent" body="Produces opportunity reports, briefs, sourced drafts, original media and publishing proposals."/><PublicCard icon={Activity} tone="amber" title="Search Optimization Agent" body="Investigates rankings, decay, technical health, links, competitors, backlinks and AI visibility."/><PublicCard icon={GitPullRequest} tone="rose" title="Site Experience Engineer" body="Matches the site architecture and design system, prepares diffs, runs builds and attaches rollback guidance."/></div></PublicSection>
    <PublicSection><div className="grid gap-12 lg:grid-cols-2"><div><PublicHeading eyebrow="Example handoff" title="A finished change, not a dashboard score." body="For a decaying API authentication guide, the team prepares a repository-native update with the complete decision context."/><PublicChecklist items={["Finding: impressions stable, CTR down after a SERP intent shift","Artifact: revised intro, comparison table, FAQ schema and two contextual internal links","Validation: source, duplication, build, metadata and broken-link checks","Approval: exact diff, preview, expected metric and rollback commit","Measurement: deployment annotation plus 28-day query and conversion observation"]}/></div><div className="marketing-card p-5 font-mono text-[11px]"><p className="text-fg-faint">PROPOSAL SF-2084 · /docs/api-auth</p><p className="mt-5 rounded-lg bg-rose/8 p-3 text-rose">- Generic setup introduction</p><p className="mt-2 rounded-lg bg-mint/8 p-3 text-mint">+ Choose OAuth for delegated access; use service tokens for server jobs.</p><p className="mt-3 rounded-lg border border-edge p-3 text-fg-mute">build ✓ links ✓ schema ✓ rollback ✓</p><p className="mt-3 text-amber">human decision required</p></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><PublicHeading eyebrow="Delivery and governance" title="Connect the systems you already trust."/><div className="mt-8 grid gap-4 sm:grid-cols-2"><PublicCard icon={GitPullRequest} title="GitHub or WordPress" body="Protected pull requests or governed WordPress proposals preserve your publishing process."/><PublicCard icon={ShieldCheck} tone="mint" title="Separate approval" body="Agents cannot approve, merge, deploy or publish through agent tools, API, CLI or MCP."/></div></div><div className="space-y-5"><div className="marketing-card p-6"><p className="text-sm font-semibold">Capacity by plan</p><PublicChecklist items={["Starter: one focused production site","Growth: three sites plus more monitoring, media and API access","Agency: ten sites, portfolio controls and higher concurrency"]}/><p className="mt-4 text-xs text-fg-faint">Capacity never implies guaranteed rankings, traffic or revenue.</p></div><PublicProofNotice/></div></div></PublicSection>
    <PublicFaq items={[["Can agents publish without permission?","No. An authenticated human must approve the exact production proposal."],["Is this a bundle of writing tools?","No. It connects opportunity discovery, existing-content improvement, delivery, validation and measurement."],["What happens when evidence is weak?","The system defers the proposal or records a hypothesis instead of inventing certainty."],["Is there a free trial?","No. Paid onboarding reserves operational capacity and establishes production safeguards."],["Does SEOForge guarantee rankings?","No. Search engines control rankings; SEOForge measures changes to the inputs you can control."]]}/>
    <PublicCta title="Choose the operating capacity for your SEO team." body="Subscribe first, complete scoped onboarding and activate both pipelines with human production approval enforced."/>
  </PublicShell>;
}

