import type { Metadata } from "next";
import { ChartNoAxesCombined, MapPin, MonitorSmartphone, Tags } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Rank Tracking with Production Context — SEOForge", description: "Track search visibility by market, device and SERP feature with deployment annotations and evidence-backed actions.", alternates: { canonical: "/platform/search-optimization/rank-tracking" } };

export default function RankTrackingPage() {
  return <PublicShell>
    <PublicHero eyebrow="Rank tracking" title="See ranking movement beside the website changes that may explain it." description="SEOForge tracks authorized keyword cohorts by engine, market, language, location and device, then attaches deployments, SERP features and investigations so a position change is never presented without context." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="Explore Search Optimization" secondaryHref="/platform/search-optimization" visual={<div className="marketing-card p-5"><div className="flex justify-between text-xs"><b>oauth vs api key · US mobile</b><span className="text-mint">18 → 9</span></div><div className="mt-5 flex h-28 items-end gap-2">{[35,42,38,52,49,65,72,79].map((h,i)=><span key={i} className="flex-1 rounded-t bg-primary/30" style={{height:`${h}%`}}/>)}</div><div className="mt-3 border-t border-dashed border-amber/30 pt-3 text-[10px] text-amber">18 Jun · comparison table deployed</div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Detection" title="A rank is an observation, not a diagnosis."/><PublicChecklist items={["Exact engine, country, language, city and device","Observed URL and competing site URLs","SERP features, volatility and result composition","Search Console clicks, impressions and CTR where authorized","Deployments, experiments and indexing events on the timeline"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Before → after example</p><p className="mt-5 text-sm"><b>Before:</b> median cohort position 18.2; comparison result absent; 2.4% CTR.</p><p className="mt-4 text-sm"><b>Approved change:</b> answer-first intro and decision table deployed June 18.</p><p className="mt-4 text-sm"><b>Observed after 28 days:</b> median 9.4; comparison result present; 3.1% CTR.</p><p className="mt-4 text-xs text-fg-faint">Observation, not proof of sole causation; seasonality and SERP changes remain visible.</p></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Tracking workflow" title="Movement becomes a prioritized investigation."/><div className="mt-10"><PublicSteps steps={["Define keyword cohorts and exact market dimensions","Collect scheduled rank and SERP observations","Compare sustained movement with visibility and click evidence","Annotate deployments, index events and competitor changes","Prioritize only material, sufficiently supported findings","Prepare a targeted change and measure the same cohort"]} accent="mint"/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={MapPin} title="Market exactness" body="Location and language remain part of every observation."/><PublicCard icon={MonitorSmartphone} tone="amber" title="Device split" body="Desktop and mobile movements are not blended into a misleading average."/><PublicCard icon={Tags} tone="mint" title="Annotations" body="Deployments, experiments and index events sit on the same timeline."/><PublicCard icon={ChartNoAxesCombined} tone="rose" title="Cohort trend" body="Priority uses sustained group movement, not one volatile daily point."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="A reviewer approves the proposed page change, not the tracking observation. Evidence, expected metric and rollback context stay attached."/><PublicCard title="Paid capacity" body="Tracked-query allowances count each market, engine, location and device combination. Plans define cadence and volume; rankings are never guaranteed."/></div></PublicSection>
    <PublicFaq items={[["How often are rankings checked?","Cadence depends on the paid plan, market priority and provider capacity shown in the workspace."],["Why does SEOForge use cohorts?","Groups reduce overreaction to one volatile query and connect work to a page or objective."],["Do annotations prove causation?","No. They establish temporal context; the report also exposes competing changes and uncertainty."],["What can a reviewer approve?","A resulting content, metadata, link or technical proposal with its baseline and observation plan."],["Can SEOForge guarantee a position?","No. Search engines control result ordering and can change it at any time."]]}/>
    <PublicCta title="Track rankings as part of an accountable production loop." body="Choose a paid plan with the query, market and observation capacity your operation needs."/>
  </PublicShell>;
}

