import type { Metadata } from "next";
import { FileCheck, LockKeyhole, PanelsTopLeft } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"WordPress SEO Automation With Publishing Approval — SEOForge",description:"Prepare governed WordPress drafts, updates and media while keeping publication human-controlled.",alternates:{canonical:"/wordpress-seo-automation"}};
export default function WordpressSeoAutomationPage(){return <PublicShell>
 <PublicHero eyebrow="WordPress SEO automation" title="Automate the workflow around WordPress without creating a publishing backdoor." description="SEOForge maps the authorized site, theme, taxonomies, editor structure and SEO configuration before preparing drafts, updates and media. The exact production action remains locked for human approval." primary="Choose Your Plan" primaryHref="/pricing" secondary="Review WordPress Integration" secondaryHref="/integrations/wordpress" visual={<div className="marketing-card p-7"><PanelsTopLeft className="text-primary"/><p className="mt-5 font-semibold">WordPress proposal</p><PublicChecklist items={["Draft and media prepared","Taxonomy and metadata checked","Preview captured","Publish action locked"]}/></div>}/>
 <PublicSection><PublicHeading eyebrow="Workflow" title="Respect the WordPress site that already exists."/><div className="mt-10"><PublicSteps steps={["Authorize the selected site with scoped access","Map editor, theme, plugins, taxonomies and media rules","Prepare content or optimization work","Validate fields, links, assets and preview","Present the exact action for human approval","Verify the live URL and record the deployment"]}/></div></PublicSection>
 <PublicSection muted><div className="grid gap-4 md:grid-cols-3"><PublicCard icon={FileCheck} title="Structured proposals" body="Titles, slugs, blocks, fields, categories, metadata and media remain visible as reviewable changes."/><PublicCard icon={LockKeyhole} title="Explicit approval" body="An agent, webhook, API, CLI or MCP client cannot approve or publish on the reviewer’s behalf."/><PublicCard icon={PanelsTopLeft} title="Production validation" body="The live page is checked for expected content, links, metadata, schema and obvious visual failure."/></div></PublicSection>
 <PublicFaq items={[["Does SEOForge need administrator access?","Permissions depend on the supported workflow. Use the least-privilege role that can perform the authorized action and review scopes during onboarding."],["Does it replace WordPress backups?","No. Keep your normal backup, staging and recovery practices; SEOForge attaches rollback guidance to its proposal."],["Can I connect a site before paying?","No. Product and provider connection access begin after paid subscription."]]}/><PublicCta title="Operate WordPress content with a visible, human-controlled production boundary." body="Choose paid capacity for the sites and monthly publishing volume you need."/>
</PublicShell>}
