import type { Metadata } from "next";
import { GitBranch, GitPullRequest, ShieldCheck } from "lucide-react";
import { PublicCard, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"GitHub Content Automation Through Protected Pull Requests — SEOForge",description:"Prepare repository-native content and SEO changes with previews, checks and human review.",alternates:{canonical:"/github-content-automation"}};
export default function GithubContentAutomationPage(){return <PublicShell>
 <PublicHero eyebrow="GitHub content automation" title="Turn SEO work into a reviewable pull request—not an untracked export." description="SEOForge understands the authorized repository, follows its conventions, creates a protected branch, validates the change and attaches evidence, screenshots and rollback context. Branch protection still decides what can merge." primary="Choose Your Plan" primaryHref="/pricing" secondary="Review GitHub Integration" secondaryHref="/integrations/github" visual={<div className="marketing-card p-7"><GitPullRequest className="text-mint"/><p className="mt-5 font-semibold">content/update-decay-guide</p><div className="mt-4 rounded-xl bg-panel-2 p-4 text-xs text-fg-mute"><p className="text-mint">+ 84 additions</p><p className="text-rose">− 19 removals</p><p className="mt-3 text-amber">awaiting reviewer approval</p></div></div>}/>
 <PublicSection><PublicHeading eyebrow="Repository-native" title="The codebase sets the implementation rules."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={GitBranch} title="Understand first" body="Detect framework, content source, routes, components, metadata, styling and required build commands."/><PublicCard icon={GitPullRequest} title="Prepare the exact diff" body="Keep content, code, media and internal links together on a bounded branch with provenance."/><PublicCard icon={ShieldCheck} title="Respect protection" body="SEOForge never bypasses required reviews, status checks or the customer’s merge authority."/></div></PublicSection>
 <PublicSection muted><PublicHeading eyebrow="Pull-request path" title="No hidden production step."/><div className="mt-9"><PublicSteps steps={["Authorize selected repositories through the GitHub App","Read allowed paths and repository conventions","Create a bounded branch and exact change","Run configured validation and capture previews","Open a proposal for authenticated human review","Let protected GitHub controls govern merge and deployment"]}/></div></PublicSection>
 <PublicFaq items={[["Can the agent merge its own pull request?","No. It cannot approve, merge, deploy, retrieve credentials or bypass branch protection."],["What if the build fails?","The proposal remains blocked with the failure visible; it is not presented as ready for production."],["Is repository access free?","No. GitHub connection and workflow execution require a paid workspace."]]}/><PublicCta title="Move SEO work through the same controls as the rest of your codebase." body="Select a paid plan for your repositories, publishing capacity and agent usage."/>
</PublicShell>}
