import type { Metadata } from "next";
import { Boxes, Radar, Scale } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "SEOForge vs Search Atlas — July 2026", description: "A balanced comparison of SEOForge and Search Atlas for SEO operations.", alternates: { canonical: "/compare/search-atlas" } };

export default function SearchAtlasComparisonPage() {
  return <PublicShell>
    <PublicHero eyebrow="Vendor-authored · reviewed 20 July 2026" title="SEOForge vs Search Atlas" description="SEOForge centers on a four-agent operating system, two continuous pipelines and a locked human approval boundary. Search Atlas is positioned as a broad SEO software platform. The right choice depends on whether you want a coordinated operator or a wider suite your team drives." primary="Choose Your Plan" primaryHref="/pricing" secondary="Book a Demo" secondaryHref="/demo" visual={<div className="marketing-card p-7"><div className="flex items-center justify-between"><Radar className="text-primary" /><Scale className="text-amber" /></div><p className="mt-7 text-lg font-semibold">Operator depth vs suite breadth</p><p className="mt-3 text-sm leading-6 text-fg-mute">Evaluate the real workflow across discovery, implementation, approval, production validation and measurement.</p></div>} />
    <PublicSection><PublicHeading eyebrow="Fit" title="Start with the operating model your team can sustain." /><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={Boxes} title="SEOForge may fit when…"><PublicChecklist items={["You want distinct Content Growth and Search Optimization queues","A Supervisor must manage priorities, conflicts, budgets and retries","Repository or WordPress changes need validation before human approval","Developer interfaces must never become production-authority backdoors"]} /></PublicCard><PublicCard icon={Radar} title="Search Atlas may fit better when…" tone="amber"><PublicChecklist items={["You prefer a broad suite of SEO functions in one product","Your specialists want to select and operate individual tools directly","Your existing process already handles governance and production delivery","A breadth-first toolkit is more important than SEOForge’s specific agent architecture"]} /></PublicCard></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Buyer checklist" title="Ask for a complete live workflow, not a slide." /><div className="mt-9 grid gap-4 md:grid-cols-3"><PublicCard title="Show the handoffs" body="Follow one finding from provider evidence through exact production change and human decision." /><PublicCard title="Test boundaries" body="Confirm tokens, agents and automations cannot approve, merge, deploy, retrieve credentials or bypass protection." /><PublicCard title="Inspect limits" body="Compare sites, tracked keywords, publishing volume, provider costs, concurrency and overage policy." /></div><p className="mt-8 text-sm text-fg-mute">This page does not make claims about Search Atlas features unavailable to us for verification. Confirm current capabilities, pricing and contractual terms with Search Atlas. SEOForge’s descriptions are vendor-authored.</p></PublicSection>
    <PublicFaq items={[["Is this an independent review?","No. SEOForge wrote it. The review date and methodology are visible so you can weigh it appropriately."],["Do you claim Search Atlas lacks automation?","No. We avoid absolute competitor claims. Ask each vendor to demonstrate the exact workflow and boundaries you require."],["Does SEOForge offer a free trial?","No. Product access begins with a paid subscription after plan selection and onboarding."]]} />
    <PublicCta title="See whether a governed operator fits better than a broad toolkit." body="Book a product walkthrough with your sites, providers and approval requirements in view." primary="Book a Demo" href="/demo" secondary="View Pricing" secondaryHref="/pricing" />
  </PublicShell>;
}
