import type { Metadata } from "next";
import { Activity, CircleDollarSign, GitCompare, ListTodo } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Workflow Supervisor Agent — SEOForge", description: "Meet the agent that routes two SEO pipelines, reserves capacity, resolves conflicts, monitors heartbeats and enforces approval.", alternates: { canonical: "/agents/workflow-supervisor" } };

export default function WorkflowSupervisorAgentPage() {
  return <PublicShell>
    <PublicHero eyebrow="Agent 01 · Workflow Supervisor" title="The accountable dispatcher for every autonomous assignment." description="This agent decides what can run, which specialist owns it, what capacity is reserved and whether overlapping work must wait. It can coordinate production proposals, but never approve them." primary="Deploy the Team" primaryHref="/pricing" secondary="Inspect Supervisor Controls" secondaryHref="/platform/workflow-supervisor" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Assignment SUP-984</p><div className="mt-4 space-y-2 text-[11px]"><p className="rounded border border-edge p-3">objective · recover decaying OAuth guide</p><p className="rounded border border-edge p-3">owner · Search Optimization Agent</p><p className="rounded border border-edge p-3">budget · 1,800 credits reserved</p><p className="rounded border border-edge p-3">lock · /guides/oauth</p><p className="rounded border border-amber/25 bg-amber/8 p-3 text-amber">terminal production state · approval required</p></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Example input" title="A signal enters as a bounded objective."/><PublicChecklist items={["Trigger: 31% non-brand click decline across 12 weeks","Site: production workspace and preferred URL","Constraints: no URL change; preserve converting troubleshooting section","Allowance: one investigation plus one bounded retry","Required output: diagnosis or no-action finding with evidence"]}/></div><div><PublicHeading eyebrow="Finished output" title="An auditable assignment and handoff ledger."/><PublicChecklist items={["Priority score with impact, confidence, risk and effort","Named specialist, permitted tools and page lock","Reserved, consumed and released capacity","Heartbeat, retry and failure events","Artifact owner and immutable human approval state"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Agent workflow" title="Route one owner through one controlled lifecycle."/><div className="mt-10"><PublicSteps steps={["Validate scope, entitlement and active-site state","Check duplicate fingerprint, page lock and dependencies","Score and enqueue against both pipelines","Reserve provider and model capacity","Monitor lease, heartbeat, retry and artifact state","Close, fail or hand the proposal to human approval"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={ListTodo} title="Queue" body="Prioritized work remains explainable and bounded."/><PublicCard icon={CircleDollarSign} tone="amber" title="Budget" body="Capacity is reserved before a specialist executes."/><PublicCard icon={Activity} tone="mint" title="Heartbeat" body="Stalled work expires without silent duplication."/><PublicCard icon={GitCompare} tone="rose" title="Conflict" body="Overlapping page or topic scope becomes one reviewed resolution."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="The Supervisor can route a validated proposal to the queue; it cannot approve, merge, deploy or publish it."/><PublicCard title="Plan boundary" body="Every plan includes supervision. Site count, concurrency, tracked work and execution capacity increase by paid tier."/></div></PublicSection>
    <PublicFaq items={[["Can the Supervisor override a plan limit?","No. Entitlement and usage checks fail closed."],["What happens when agents conflict?","Work is serialized, combined or returned for a human decision with both scopes visible."],["Can it retry indefinitely?","No. Retry classes, attempts, backoff and reserved budget are bounded."],["Can it publish on a schedule?","No. Schedules can begin preparation; production still requires human approval."],["Does priority imply guaranteed impact?","No. Priority is an operating decision based on current evidence and uncertainty."]]}/>
    <PublicCta title="Deploy an autonomous team with an accountable dispatcher." body="Choose a paid plan to activate supervised queues, budgets and protected production handoffs."/>
  </PublicShell>;
}

