import type { Metadata } from "next";
import { CheckCircle2, ClipboardCheck, Scale } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "SEOForge vs Surfer SEO — July 2026", description: "A balanced, vendor-authored comparison of SEOForge and Surfer SEO operating models.", alternates: { canonical: "/compare/surfer-seo" } };

export default function SurferSeoComparisonPage() {
  return <PublicShell>
    <PublicHero eyebrow="Vendor-authored · reviewed 20 July 2026" title="SEOForge vs Surfer SEO" description="SEOForge is designed to operate two continuous pipelines through governed production proposals. Surfer SEO is widely positioned around content optimization and related content workflows. This comparison helps you choose the job—not declare a universal winner." primary="Choose Your Plan" primaryHref="/pricing" secondary="See the Workflow" secondaryHref="/how-it-works" visual={<div className="marketing-card p-7"><Scale className="text-primary" /><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-primary/10 p-4"><p className="text-xs text-primary">SEOForge</p><p className="mt-2 text-sm font-semibold">Ongoing site operations</p></div><div className="rounded-xl bg-amber/10 p-4"><p className="text-xs text-amber">Surfer</p><p className="mt-2 text-sm font-semibold">Focused content workflow</p></div></div><p className="mt-4 text-xs leading-5 text-fg-faint">Verify current Surfer capabilities and terms on its official site before purchasing.</p></div>} />
    <PublicSection><PublicHeading eyebrow="Decision frame" title="The dividing line is operational ownership." body="Choose based on how much of research, implementation, approval and measurement you want one system to coordinate." /><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={ClipboardCheck} title="SEOForge may fit when…"><PublicChecklist items={["You want new-content and existing-content pipelines operating together","GitHub or WordPress proposals must include evidence, validation and rollback context","A human must explicitly approve every production action","Budgets, agent activity and post-deployment measurement belong in one control room"]} /></PublicCard><PublicCard icon={CheckCircle2} title="Surfer may fit better when…" tone="amber"><PublicChecklist items={["Your primary need is an editor-centered content optimization workflow","Writers want hands-on guidance while drafting or refreshing individual pages","Your team already owns publishing, technical implementation and measurement","You prefer adding a focused content tool to an existing SEO stack"]} /></PublicCard></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="What to verify" title="Run the same buying test with both vendors." /><div className="mt-9 grid gap-4 md:grid-cols-3"><PublicCard title="Production boundary" body="Ask exactly what can create, approve, merge, publish and roll back a live change." /><PublicCard title="Evidence model" body="Inspect how sources, timestamps, hypotheses and measured outcomes are distinguished." /><PublicCard title="Total workflow cost" body="Include editorial labor, integrations, implementation, monitoring and the plan limits you actually need." /></div><p className="mt-8 text-sm leading-6 text-fg-mute">Methodology: SEOForge describes its own product from current internal specifications. Competitor characterization is intentionally high level and should be confirmed against Surfer’s current official documentation. We do not claim access to Surfer’s private roadmap, performance data or customer outcomes.</p></PublicSection>
    <PublicFaq items={[["Does SEOForge claim Surfer cannot publish content?","No. Capabilities change and may depend on integrations or plans. Verify the current Surfer workflow directly; our distinction is SEOForge’s emphasis on governed end-to-end site operations."],["Is either platform guaranteed to improve rankings?","No. Search engines remain external systems. Evaluate evidence quality, workflow fit and measurement discipline instead of ranking promises."],["Can I try SEOForge free?","No. SEOForge is a paid product. Review pricing or book a demo before subscribing."]]} />
    <PublicCta title="Choose the system that owns the right amount of work." body="If you need continuous investigation, production proposals and measured outcomes under human approval, review SEOForge paid plans." />
  </PublicShell>;
}
