import type { Metadata } from "next";
import { FileDiff, Link2, TrendingDown } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"AI Content Optimization Software — SEOForge",description:"Investigate decay, intent mismatch, competition and conversion evidence before proposing page changes.",alternates:{canonical:"/ai-content-optimization-software"}};
export default function AiContentOptimizationSoftwarePage(){return <PublicShell>
 <PublicHero eyebrow="AI content optimization" title="Change the page because the evidence supports it—not because a score turned red." description="SEOForge investigates visibility loss, intent mismatch, missing evidence, internal links, competing pages and conversion context before preparing a targeted refresh, consolidation or no-change decision." primary="Choose Your Plan" primaryHref="/pricing" secondary="Explore Content Refresh" secondaryHref="/platform/search-optimization/content-refresh" visual={<div className="marketing-card p-7"><FileDiff className="text-primary"/><p className="mt-5 text-sm font-semibold">Illustrative refresh decision</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-rose/10 p-3 text-rose">decay</span><span className="rounded-lg bg-amber/10 p-3 text-amber">intent</span><span className="rounded-lg bg-mint/10 p-3 text-mint">update</span></div><p className="mt-4 text-xs text-fg-faint">Hypothesis—not a customer result.</p></div>}/>
 <PublicSection><PublicHeading eyebrow="Decision quality" title="Update, consolidate, redirect—or leave the page alone."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={TrendingDown} title="Find sustained decay" body="Use comparable windows, query mix, seasonality and conversion evidence instead of reacting to one daily fluctuation."/><PublicCard icon={Link2} title="Inspect the site graph" body="Check cannibalization, internal links, topic relationships and the preferred destination before changing copy."/><PublicCard icon={FileDiff} title="Propose the minimum change" body="Show the exact diff, expected impact, risk, validation and rollback context for human approval."/></div></PublicSection>
 <PublicSection muted><div className="grid gap-7 lg:grid-cols-2"><div><PublicHeading eyebrow="Evidence pack" title="A refresh proposal should answer six questions."/><PublicChecklist items={["What changed, and over which comparable period?","Which queries and intents were affected?","Did the SERP, competitors or our own site change?","What is the smallest defensible intervention?","How will production be validated?","When and by which metric will we judge it?"]}/></div><PublicCard title="When no change is correct" body="A short-lived movement, weak evidence, seasonality or a page already satisfying its role may justify monitoring rather than editing. SEOForge records the decision instead of manufacturing work." tone="mint"/></div></PublicSection>
 <PublicFaq items={[["Does SEOForge optimize to a universal content score?","No single score establishes search quality. SEOForge combines provider, page, SERP and business evidence."],["Can it rewrite a page automatically?","It can prepare a proposed rewrite, but publication requires human approval."],["Are results guaranteed?","No. The system measures outcomes and preserves uncertainty."]]}/><PublicCta title="Give every existing page an evidence-backed owner." body="Deploy the paid Search Optimization pipeline for continuous investigation and controlled implementation."/>
</PublicShell>}
