import type { Metadata } from "next";
import { Activity, CircleDollarSign, GitCompareArrows, ListOrdered, RefreshCcw, ShieldCheck } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Workflow Supervisor — SEOForge", description: "Control agent queues, schedules, budgets, heartbeats, conflicts, retries, usage and human approval across two SEO pipelines.", alternates: { canonical: "/platform/workflow-supervisor" } };

export default function WorkflowSupervisorPage() {
  return <PublicShell>
    <PublicHero eyebrow="Workflow Supervisor" title="Autonomous work stays prioritized, non-duplicative and inside budget." description="The Supervisor coordinates both pipelines without becoming a production backdoor. It reserves capacity, watches agent heartbeats, resolves overlapping page scope, applies retry policy and enforces human approval." primary="Book a Supervisor Demo" primaryHref="/demo" secondary="Compare Paid Plans" secondaryHref="/pricing" visual={<div className="marketing-card p-5"><div className="grid grid-cols-3 gap-2 text-center text-[10px]"><span className="rounded border border-edge p-3">queued<br/><b className="text-primary">12</b></span><span className="rounded border border-edge p-3">running<br/><b className="text-mint">3</b></span><span className="rounded border border-edge p-3">approval<br/><b className="text-amber">5</b></span></div><div className="mt-3 rounded-xl border border-edge bg-[#080a0f] p-4 font-mono text-[10px]"><p className="text-mint">CG-441 heartbeat · 14s ago</p><p className="mt-2 text-amber">SO-731 retry 1/2 · provider 429</p><p className="mt-2 text-rose">conflict · /guides/oauth locked</p><p className="mt-2 text-fg-mute">budget · 28,400 / 40,000 credits</p></div></div>} />
    <PublicSection><PublicHeading eyebrow="Control plane" title="Every assignment has an owner, allowance and terminal state."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><PublicCard icon={ListOrdered} title="Priority queues" body="Urgency, impact, confidence, risk, deadline and dependency determine order across both pipelines."/><PublicCard icon={CircleDollarSign} tone="amber" title="Budgets and usage" body="Capacity is reserved before execution; exhausted work stops safely instead of creating silent overages."/><PublicCard icon={Activity} tone="mint" title="Heartbeats" body="Leases and progress events expose stalled workers without duplicating the assignment."/><PublicCard icon={GitCompareArrows} tone="rose" title="Conflict resolution" body="Overlapping URL, topic or repository scope is serialized, merged or returned for a decision."/><PublicCard icon={RefreshCcw} title="Retry handling" body="Only transient failures retry, with bounded attempts, backoff and preserved evidence."/><PublicCard icon={ShieldCheck} tone="mint" title="Approval enforcement" body="No agent or retry can cross the authenticated human production boundary."/></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Scheduling logic" title="The highest-value safe work moves first."/><div className="mt-10"><PublicSteps steps={["Receive scheduled, provider-triggered or human-requested work","Check duplicate fingerprints, page locks and dependencies","Score impact, confidence, urgency, effort and production risk","Reserve site, provider and model capacity from the paid allowance","Assign one specialist with a lease and heartbeat deadline","Retry transient failure or route terminal failure with evidence","Release capacity and require approval for any production proposal"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Conflict example" title="Two agents want the same guide. One reviewable change survives."/><PublicChecklist items={["Content Growth requests a new OAuth comparison section","Search Optimization requests a refresh after confirmed decay","Supervisor detects identical preferred URL and overlapping intent","Search finding becomes the parent assignment; new research is attached","One combined proposal enters approval with one capacity ledger"]}/></div><div className="marketing-card p-6"><p className="text-sm font-semibold">Failure example · provider rate limit</p><p className="mt-4 text-sm leading-6 text-fg-mute">Attempt 1 records the 429 and releases the worker. Backoff schedules one retry inside the reserved budget. A second transient failure closes the run as blocked and preserves partial evidence; it does not loop, overspend or publish incomplete work.</p></div></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Usage controls by plan" body="Plans cap sites, tracked queries, provider operations, model work, content, media and concurrency. The ledger shows reserved, consumed and released capacity."/><PublicCard title="Human authority" body="Schedules can start research and preparation. Only an authenticated reviewer can approve the exact GitHub or WordPress production proposal."/></div></PublicSection>
    <PublicFaq items={[["Can two agents create duplicate articles?","Duplicate fingerprints, topic ownership, active assignments and URL locks are checked before work begins."],["Can agents overspend?","Runs reserve capacity first and fail closed when an allowance is unavailable."],["What if an agent stops responding?","Its lease expires, partial evidence is preserved and bounded recovery policy decides whether to retry or fail."],["Can a retry publish work?","No. Retry policy cannot change the production approval boundary."],["How is priority decided?","Impact, confidence, urgency, effort, risk, dependencies and paid capacity remain visible in the score."]]}/>
    <PublicCta title="Put an accountable supervisor above both autonomous pipelines." body="Book a paid product walkthrough to inspect queues, budgets, conflicts, retries and approval enforcement." primary="Book a Product Walkthrough" href="/demo"/>
  </PublicShell>;
}

