import type { Metadata } from "next";
import { FileDiff, Link, ListRestart, TestTubeDiagonal } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Evidence-Backed Content Refresh — SEOForge", description: "Prepare exact content refreshes from observed decay, intent and conversion evidence, then validate and measure the result.", alternates: { canonical: "/platform/search-optimization/content-refresh" } };

export default function ContentRefreshPage() {
  return <PublicShell>
    <PublicHero eyebrow="Content refresh" title="Change only what the evidence says has gone stale." description="SEOForge turns a confirmed finding into a line-level editorial proposal: outdated claims replaced, missing decisions added, weak structure repaired and useful sections preserved." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="See Decay Detection" secondaryHref="/platform/search-optimization/content-decay" visual={<div className="marketing-card p-5 font-mono text-[11px]"><p className="text-fg-faint">refresh /guides/oauth</p><p className="mt-4 rounded bg-rose/8 p-3 text-rose">- OAuth is always the most secure choice.</p><p className="mt-2 rounded bg-mint/8 p-3 text-mint">+ Choose OAuth for delegated user access; use scoped service credentials for bounded server workloads.</p><p className="mt-3 text-mint">+ decision table · +2 verified examples</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Refresh input" title="A diagnosis defines the edit boundary."/><PublicChecklist items={["Loss concentrated in comparison and implementation queries","Two security claims now overstate the cited sources","Current intro delays the decision answer by 430 words","Three linked product routes changed since publication","High-performing troubleshooting section should remain untouched"]}/></div><div><PublicHeading eyebrow="Finished change" title="Review the exact page that will replace production."/><PublicChecklist items={["Answer-first introduction with scoped recommendation","New tradeoff table and two source-verified examples","Updated product links and descriptive anchors","Preserved troubleshooting section and existing conversion event","Preview, content diff, build checks and rollback commit"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Refresh workflow" title="Diagnose, edit, validate and observe."/><div className="mt-10"><PublicSteps steps={["Lock the finding, baseline and preferred page intent","Map outdated, missing, redundant and still-useful sections","Verify new sources and product facts","Prepare a bounded content, link and metadata diff","Run editorial, build, schema and broken-link checks","Require approval, deploy and observe the original cohort"]}/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={ListRestart} title="Preserve" body="Keep sections already serving the reader and baseline."/><PublicCard icon={FileDiff} tone="mint" title="Replace" body="Revise only claims and structures supported by the diagnosis."/><PublicCard icon={Link} tone="amber" title="Reconnect" body="Update product paths and add contextual internal links."/><PublicCard icon={TestTubeDiagonal} tone="rose" title="Measure" body="Compare the same query and conversion cohorts after deployment."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human approval" body="The reviewer sees source changes, exact text diff, preview, expected metric, risk and rollback. Revisions return to validation."/><PublicCard title="Capacity and attribution" body="Refresh volume uses paid execution capacity. Reported before/after changes include dates, cohorts and confounders rather than causal certainty."/></div></PublicSection>
    <PublicFaq items={[["When is a rewrite better than a refresh?","When the page’s audience task, structure and factual base no longer support a bounded edit."],["Can SEOForge preserve strong sections?","Yes. The edit plan explicitly labels content to keep, revise, remove or add."],["Does a refresh change the URL?","Usually not. Consolidation or redirect is proposed separately when evidence supports it."],["What does the human approve?","The exact content, link, metadata and production diff with validation and rollback."],["Will the page recover its old rankings?","No outcome is guaranteed; SEOForge observes the defined cohort after deployment."]]}/>
    <PublicCta title="Turn a confirmed decline into a precise, reviewable refresh." body="Choose a paid plan to connect decay evidence with production-ready editorial changes."/>
  </PublicShell>;
}

