import type { Metadata } from "next";
import { BookOpenCheck, RefreshCw, Scale } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "SEOForge vs Frase — July 2026", description: "A fair comparison of SEOForge continuous operations and Frase content workflows.", alternates: { canonical: "/compare/frase" } };

export default function FraseComparisonPage() {
  return <PublicShell>
    <PublicHero eyebrow="Vendor-authored · reviewed 20 July 2026" title="SEOForge vs Frase" description="SEOForge coordinates ongoing content creation, existing-page optimization and governed site delivery. Frase is commonly positioned around research, briefs, writing and optimization. Choose based on whether your bottleneck is the content workspace or the wider operating loop." primary="Choose Your Plan" primaryHref="/pricing" secondary="See the Workflow" secondaryHref="/how-it-works" visual={<div className="marketing-card p-7"><Scale className="text-primary" /><div className="mt-7 flex items-center gap-4"><BookOpenCheck className="text-amber" /><span className="h-px flex-1 bg-edge"/><RefreshCw className="text-mint" /></div><p className="mt-5 text-sm text-fg-mute">Brief-and-editor depth compared with continuous investigation, delivery and measurement.</p></div>} />
    <PublicSection><PublicHeading eyebrow="Fit scenarios" title="A focused content workflow can be the better decision." /><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={RefreshCw} title="SEOForge may fit when…"><PublicChecklist items={["You need continuous monitoring as well as new-content production","The workflow must coordinate multiple agents and prevent conflicts","Implementation goes through validated GitHub or WordPress proposals","Production outcomes must feed the next prioritization cycle"]} /></PublicCard><PublicCard icon={BookOpenCheck} title="Frase may fit better when…" tone="amber"><PublicChecklist items={["Your team mainly needs research, briefing and writing assistance","Editors want a focused workspace for individual content assignments","Publishing and performance workflows are already mature elsewhere","You do not need SEOForge’s agent orchestration or production-delivery layer"]} /></PublicCard></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Evaluate directly" title="Use a decay refresh and a new article as separate tests." /><div className="mt-9 grid gap-4 md:grid-cols-3"><PublicCard title="Opportunity selection" body="Can the system explain why this assignment outranks competing work?" /><PublicCard title="Editorial integrity" body="Can reviewers inspect sources, claims, intent, duplication and brand constraints?" /><PublicCard title="Production control" body="Does the exact approved artifact reach your site with validation and rollback context?" /></div><p className="mt-8 text-sm text-fg-mute">Reviewed from SEOForge’s perspective on 20 July 2026. Confirm Frase’s current product, prices, limits and integrations with Frase. We do not infer private capabilities or claim comparative ranking outcomes.</p></PublicSection>
    <PublicFaq items={[["Is Frase only an AI writer?","We do not characterize it that narrowly. It is publicly associated with research and optimization workflows; verify its full current scope directly."],["Which product is easier for a writer?","That depends on the team and assignment. A focused editor may fit an individual writer better; SEOForge is designed around the site-wide operating system."],["Can SEOForge be evaluated without buying?","You can read public pages and book a demo, but product access begins only after paid subscription."]]} />
    <PublicCta title="Move from individual content tasks to a governed operating loop." body="If that is the job, compare SEOForge paid plans and implementation capacity." />
  </PublicShell>;
}
