import type { Metadata } from "next";
import { Combine, GitMerge, Network, Split } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Keyword Cannibalization Detection — SEOForge", description: "Distinguish healthy multi-page coverage from harmful intent overlap and prepare consolidation or differentiation changes.", alternates: { canonical: "/platform/search-optimization/cannibalization" } };

export default function CannibalizationPage() {
  return <PublicShell>
    <PublicHero eyebrow="Cannibalization" title="Shared keywords are not the problem. Confused page ownership is." description="SEOForge tests whether multiple URLs genuinely compete for the same searcher task, then prepares the safest differentiation, consolidation, redirect and internal-link changes." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="Explore Search Optimization" secondaryHref="/platform/search-optimization" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">Intent ownership · API authentication</p><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-[10px]"><span className="rounded-xl border border-rose/25 bg-rose/8 p-4">/blog/api-auth<br/><b>comparison + setup</b></span><span className="text-rose">×</span><span className="rounded-xl border border-rose/25 bg-rose/8 p-4">/docs/auth<br/><b>setup + comparison</b></span></div><p className="mt-4 rounded-lg border border-mint/25 bg-mint/8 p-3 text-[11px] text-mint">Proposal: comparison → blog · implementation → docs</p></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Evidence collected" title="Confirm actual overlap before merging anything."/><PublicChecklist items={["Query-to-URL switching across a stable observation window","Search intent and SERP result-type similarity","Content section and entity overlap","Internal-link anchors pointing to competing destinations","Clicks, conversions, backlinks and business role for each URL"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Before → proposed ownership</p><p className="mt-5 text-sm"><b>Before:</b> both /blog/api-auth and /docs/auth alternate for comparison queries; neither holds stable ownership.</p><p className="mt-4 text-sm"><b>Change:</b> preserve the blog as the decision guide, narrow docs to implementation, move duplicated examples and update 14 internal anchors.</p><p className="mt-4 text-sm"><b>Validation:</b> redirects not required; canonical self-references preserved; link graph re-crawled.</p></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Resolution workflow" title="Choose the smallest change that makes page ownership clear."/><div className="mt-10"><PublicSteps steps={["Detect persistent query and URL ownership switching","Compare intent, content, links and conversion roles","Rule out healthy multi-page coverage","Choose differentiate, consolidate, redirect or observe","Prepare content, canonical, redirect and link implications","Approve, deploy, validate and track preferred URL stability"]} accent="mint"/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={Split} title="Differentiate" body="Give each useful URL a distinct audience task."/><PublicCard icon={Combine} tone="mint" title="Consolidate" body="Move unique value into one stronger preferred page."/><PublicCard icon={GitMerge} tone="amber" title="Redirect" body="Preserve destination and link implications in the proposal."/><PublicCard icon={Network} tone="rose" title="Relink" body="Update internal anchors so the site reinforces page ownership."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Redirects and consolidation can be destructive, so reviewers see retained content, destination logic, inbound links, preview and rollback."/><PublicCard title="Capacity and measurement" body="URL analysis and execution use paid capacity. Success is observed as stable preferred ownership and useful traffic—not a guaranteed rank increase."/></div></PublicSection>
    <PublicFaq items={[["Do two pages ranking for one keyword mean cannibalization?","No. The pages must materially overlap in intent and weaken preferred ownership."],["Can SEOForge delete a page?","No agent deletes production content. It prepares a reviewed consolidation or redirect proposal."],["How are backlinks handled?","Inbound links, redirect targets and retained unique content remain visible before approval."],["What does the reviewer approve?","Content moves, target URL, redirects, canonicals, internal-link changes and rollback."],["Does consolidation guarantee better rankings?","No. It clarifies page ownership; actual search outcomes are measured."]]}/>
    <PublicCta title="Give every search intent a clear, deliberate page owner." body="Choose a paid plan to detect harmful overlap and govern the exact resolution."/>
  </PublicShell>;
}
