import type { Metadata } from "next";
import { Activity, BellRing, Microscope } from "lucide-react";
import { PublicCard, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";
export const metadata:Metadata={title:"Continuous SEO Monitoring That Prepares the Response — SEOForge",description:"Detect meaningful search changes, investigate evidence and route validated work for approval.",alternates:{canonical:"/continuous-seo-monitoring"}};
export default function ContinuousSeoMonitoringPage(){return <PublicShell>
 <PublicHero eyebrow="Continuous SEO monitoring" title="Do more than alert the team that something changed." description="SEOForge separates noisy observations from material findings, investigates likely causes and prepares the smallest supported response for human review." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="See Search Optimization" secondaryHref="/platform/search-optimization" visual={<div className="marketing-card p-7"><Activity className="text-mint"/><p className="mt-5 font-semibold">Observation → investigation → proposal</p><div className="mt-6 space-y-2 text-xs"><p className="rounded-lg bg-panel-2 p-3">Position loss exceeds configured threshold</p><p className="rounded-lg bg-panel-2 p-3">SERP and page evidence refreshed</p><p className="rounded-lg bg-amber/10 p-3 text-amber">Human decision required</p></div></div>}/>
 <PublicSection><PublicHeading eyebrow="Signal discipline" title="Monitor changes that deserve an operational response."/><div className="mt-10 grid gap-4 md:grid-cols-3"><PublicCard icon={BellRing} title="Detect" body="Track rankings, pages, technical health, competitors, links and provider failures with freshness context."/><PublicCard icon={Microscope} title="Investigate" body="Compare timelines, deployments, intent, page changes and corroborating sources before assigning a cause."/><PublicCard icon={Activity} title="Measure" body="Attach baselines and observation windows to approved changes, then recommend retain, iterate or revert."/></div></PublicSection>
 <PublicSection muted><PublicHeading eyebrow="Runbook" title="Every alert must earn its way into the queue."/><div className="mt-9"><PublicSteps steps={["Observe a configured change","Check freshness and rule out provider failure","Collect page, query, SERP and deployment context","Score impact, confidence, effort and risk","Prepare or defer the response","Measure only after an approved production change"]}/></div></PublicSection>
 <PublicFaq items={[["Does every ranking movement create work?","No. Thresholds, persistence, business value and corroborating evidence prevent empty churn."],["Can monitoring explain causation?","Not automatically. SEOForge distinguishes observations and hypotheses from proven causes."],["Is this a one-time audit?","No. It is paid continuous operation with schedules, quotas and provider connections."]]}/><PublicCta title="Turn monitoring into a controlled response loop." body="Choose paid tracked-keyword and site capacity that matches your operating surface."/>
</PublicShell>}
