import type { Metadata } from "next";
import { CalendarClock, ChartSpline, SearchCheck, TriangleAlert } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Content Decay Detection — SEOForge", description: "Detect sustained losses in organic visibility or conversion value and distinguish decay from noise before changing a page.", alternates: { canonical: "/platform/search-optimization/content-decay" } };

export default function ContentDecayPage() {
  return <PublicShell>
    <PublicHero eyebrow="Content decay" title="Know which page is truly declining—and which one simply had a noisy week." description="SEOForge compares page and query cohorts across meaningful windows, accounts for seasonality and site changes, and prepares a diagnosis before recommending refresh, consolidation or observation." primary="Choose an Optimization Plan" primaryHref="/pricing" secondary="See Content Refresh" secondaryHref="/platform/search-optimization/content-refresh" visual={<div className="marketing-card p-5"><p className="text-xs font-semibold">/guides/oauth · 12-week cohort</p><div className="mt-5 flex h-28 items-end gap-2">{[88,83,78,69,70,62,58,51].map((h,i)=><span key={i} className="flex-1 rounded-t bg-rose/30" style={{height:`${h}%`}}/>)}</div><div className="mt-4 grid grid-cols-2 gap-3 text-[10px]"><span className="rounded border border-edge p-3">non-brand clicks<br/><b className="text-rose">−31%</b></span><span className="rounded border border-edge p-3">qualified conversions<br/><b className="text-rose">−18%</b></span></div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-2"><div><PublicHeading eyebrow="Evidence threshold" title="Decline is confirmed across more than one signal."/><PublicChecklist items={["Twelve-week page and non-brand query cohort","Year-over-year and preceding-period context where available","Impressions, clicks, CTR, position and landing-page conversion","SERP intent and competing-result changes","Deployments, migrations, analytics changes and known seasonality"]}/></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Finished decay finding</p><p className="mt-5 text-sm"><b>Before:</b> 4,180 non-brand clicks and 126 qualified progressions per 28 days.</p><p className="mt-3 text-sm"><b>Current:</b> 2,884 clicks and 103 progressions.</p><p className="mt-3 text-sm"><b>Diagnosis:</b> sustained loss concentrated in comparison-intent queries; page remains indexed and technically healthy.</p><p className="mt-3 text-sm"><b>Action:</b> targeted refresh, not a full rewrite.</p></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Decay workflow" title="Confirm the pattern before reserving change capacity."/><div className="mt-10"><PublicSteps steps={["Create stable page and query baselines","Detect sustained visibility, engagement or conversion loss","Check seasonality, tracking, indexation and deployments","Inspect which intents and sections lost relevance","Prioritize severity, confidence, business value and effort","Route refresh, consolidate, redirect or observe decision"]} accent="amber"/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={ChartSpline} title="Trend" body="Sustained cohort movement matters more than a single comparison point."/><PublicCard icon={CalendarClock} tone="amber" title="Time context" body="Seasonality and observation windows remain visible."/><PublicCard icon={SearchCheck} tone="mint" title="Intent shift" body="SERP composition helps explain what the search task now rewards."/><PublicCard icon={TriangleAlert} tone="rose" title="Confounders" body="Tracking changes, migrations and broad site incidents can invalidate the diagnosis."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human review" body="Approve the diagnosis and recommended action before drafting. A decay alert alone cannot alter the page."/><PublicCard title="Capacity and outcomes" body="Historical ingestion and monitoring consume plan capacity. After an approved change, the same baseline cohort measures observed recovery or further decline."/></div></PublicSection>
    <PublicFaq items={[["How long before a decline counts as decay?","The window depends on query volume, seasonality and collection cadence; SEOForge exposes the threshold used."],["Does every declining page need a rewrite?","No. The correct action may be a small refresh, consolidation, redirect or continued observation."],["Can analytics changes create false decay?","Yes. Tracking and migration events are checked before a finding is confirmed."],["What does a human approve?","The diagnosis, action type, scope, baseline and capacity reservation."],["Does a refresh guarantee recovery?","No. The system measures what happens; search engines decide visibility."]]}/>
    <PublicCta title="Find real decay before valuable pages quietly disappear." body="Choose a paid plan to monitor stable cohorts and route confirmed findings into governed optimization."/>
  </PublicShell>;
}

