import type { Metadata } from "next";
import { FileText, GitPullRequest, Scale } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "SEOForge vs Jasper — July 2026", description: "A balanced comparison of SEOForge search operations and Jasper marketing content workflows.", alternates: { canonical: "/compare/jasper" } };

export default function JasperComparisonPage() {
  return <PublicShell>
    <PublicHero eyebrow="Vendor-authored · reviewed 20 July 2026" title="SEOForge vs Jasper" description="SEOForge is purpose-built for continuous SEO operations, evidence-backed site proposals and measured outcomes. Jasper is positioned as a broader AI marketing content platform. Neither framing makes the other product inherently better." primary="See SEOForge Work" primaryHref="/how-it-works" secondary="View Pricing" secondaryHref="/pricing" visual={<div className="marketing-card p-7"><Scale className="text-primary" /><div className="mt-6 space-y-3"><div className="flex items-center gap-3 rounded-xl border border-edge p-4"><GitPullRequest className="text-mint" size={18}/><span className="text-sm">SEO operations → production proposal</span></div><div className="flex items-center gap-3 rounded-xl border border-edge p-4"><FileText className="text-amber" size={18}/><span className="text-sm">Marketing creation → team workflow</span></div></div></div>} />
    <PublicSection><PublicHeading eyebrow="Who each model serves" title="Compare the job surrounding the generated words." /><div className="mt-10 grid gap-4 lg:grid-cols-2"><PublicCard icon={GitPullRequest} title="SEOForge may fit when…"><PublicChecklist items={["Search opportunity, decay, links and technical health must stay monitored","Output must become a site-native GitHub or WordPress proposal","Provider evidence and exact production diffs belong together","You need post-deployment search and conversion observation"]} /></PublicCard><PublicCard icon={FileText} title="Jasper may fit better when…" tone="amber"><PublicChecklist items={["Your primary objective spans marketing formats beyond SEO operations","Human marketers want a general content creation environment","Your team already owns SEO research, implementation and measurement","Flexible marketing production matters more than a dedicated four-agent SEO system"]} /></PublicCard></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Proof request" title="Bring one representative assignment to both demos." body="Use the same source material, brand constraints and production destination." /><div className="mt-9 grid gap-4 md:grid-cols-3"><PublicCard title="Source discipline" body="Ask how claims, citations, freshness and unsupported statements are surfaced for review." /><PublicCard title="Website fit" body="Inspect whether output matches the real information architecture, design system and publishing controls." /><PublicCard title="Outcome loop" body="Ask what gets measured, over what baseline and observation window, after an approved change." /></div><p className="mt-8 text-sm text-fg-mute">Competitor information is deliberately limited to broad public positioning. Verify Jasper’s current features, plans and data practices through official materials. No competitor customer results are asserted here.</p></PublicSection>
    <PublicFaq items={[["Can SEOForge replace every marketing writing tool?","No. SEOForge is scoped to content and search operations. A general marketing platform may be more suitable for campaigns and formats outside that scope."],["Can Jasper perform SEO work?","Its current capabilities may support SEO-related tasks. The key evaluation is whether the complete governed workflow matches your needs; verify this directly with Jasper."],["Does SEOForge generate and publish without review?","It can prepare content and production proposals, but an authenticated human must approve the exact change."]]} />
    <PublicCta title="Choose purpose-built search operations when the surrounding workflow matters." body="Review SEOForge’s paid capacity or book a walkthrough. No free product access is offered." />
  </PublicShell>;
}
