import type { Metadata } from "next";
import { Accessibility, BadgeCheck, Fingerprint, ScanSearch } from "lucide-react";
import { PublicCard, PublicChecklist, PublicCta, PublicFaq, PublicHeading, PublicHero, PublicSection, PublicShell, PublicSteps } from "@/components/marketing/PublicPrimitives";

export const metadata: Metadata = { title: "Editorial Review for AI Content — SEOForge", description: "Review claims, sources, intent, originality, accessibility, brand voice and conversion purpose before publishing.", alternates: { canonical: "/platform/content-growth/editorial-review" } };

export default function EditorialReviewPage() {
  return <PublicShell>
    <PublicHero eyebrow="Editorial review" title="The draft is not done when the last paragraph appears." description="SEOForge examines the complete article against its approved brief: claim support, search intent, brand rules, originality, internal links, accessibility and conversion purpose. Unresolved risk stays visible to a human editor." primary="Choose a Content Plan" primaryHref="/pricing" secondary="See Human Approval" secondaryHref="/platform/human-approval" visual={<div className="marketing-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold">Editorial gate · ED-118</p><span className="rounded-full bg-amber/10 px-3 py-1 text-[10px] text-amber">2 issues</span></div><div className="mt-5 space-y-2 text-xs">{[["Intent match","pass","text-mint"],["Source coverage","pass","text-mint"],["Brand voice","review","text-amber"],["Absolute security claim","blocked","text-rose"]].map(([n,s,c])=><p key={n} className="flex justify-between rounded-lg border border-edge p-3"><span>{n}</span><span className={c}>{s}</span></p>)}</div></div>} />
    <PublicSection><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><PublicHeading eyebrow="Example review" title="A confident sentence can still be a production blocker." body="The draft claimed API keys are “always less secure.” The evidence supported narrower tradeoffs, not an absolute conclusion."/><div className="mt-6 rounded-xl border border-rose/25 bg-rose/8 p-5 text-sm text-rose">Blocked: “API keys are always less secure than OAuth.”</div><div className="mt-3 rounded-xl border border-mint/25 bg-mint/8 p-5 text-sm text-mint">Proposed: “OAuth adds delegated authorization and revocation controls; scoped API keys can remain appropriate for bounded server jobs.”</div></div><div className="marketing-card p-6"><p className="text-[10px] uppercase tracking-[.18em] text-fg-faint">Finished review report</p><PublicChecklist items={["11 consequential claims checked; 9 supported, 2 revised","Intent coverage confirmed against approved comparison brief","One repetitive section removed; 214 words reduced","Four internal links verified for target and anchor fit","Diagram alt text revised for decision sequence","Recommendation: approve after named-editor confirmation"]}/></div></div></PublicSection>
    <PublicSection muted><PublicHeading eyebrow="Editorial workflow" title="Quality gates create decisions, not vague scores."/><div className="mt-10"><PublicSteps steps={["Compare the draft with the approved brief and user task","Verify consequential claims against the source ledger","Check originality, overlap and consistency with existing pages","Review voice, prohibited language and conversion integrity","Validate links, structure, readability and accessibility","Route exact revisions and residual risk to a human editor"]} accent="mint"/></div></PublicSection>
    <PublicSection><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><PublicCard icon={ScanSearch} title="Evidence" body="Unsupported or overstated claims receive line-level findings."/><PublicCard icon={Fingerprint} tone="rose" title="Originality" body="Purpose and structure must add value beyond source or competitor phrasing."/><PublicCard icon={Accessibility} tone="amber" title="Accessibility" body="Headings, link labels, image alternatives and reading sequence are reviewed."/><PublicCard icon={BadgeCheck} tone="mint" title="Brand integrity" body="Terminology, tone, promises and conversion intent match approved rules."/></div></PublicSection>
    <PublicSection muted><div className="grid gap-6 lg:grid-cols-2"><PublicCard title="Human decision" body="The named editor accepts revisions, edits further or rejects the draft. Editorial approval still does not bypass separate production approval."/><PublicCard title="Paid capacity" body="Review depth, article volume and model usage operate within plan limits. The workspace shows consumed capacity and stops safely at the cap."/></div></PublicSection>
    <PublicFaq items={[["Is editorial review just a grammar check?","No. It covers evidence, intent, originality, brand rules, structure, links, accessibility and conversion integrity."],["Does a passing review publish the article?","No. Editorial acceptance and production approval are separate decisions."],["Can reviewers edit the draft?","Yes. Human edits become part of the proposal and material changes can trigger targeted rechecks."],["Do you use an AI-detection score?","No single detector establishes quality or authorship. SEOForge reviews the actual evidence and content characteristics."],["Can editorial review guarantee performance?","No. It improves production quality; actual search and business outcomes are observed after publishing."]]}/>
    <PublicCta title="Put a real editorial gate between generation and production." body="Choose a paid content plan to attach sources, brand rules and accountable human review to every article."/>
  </PublicShell>;
}
